### ISSUE TITLE
renderStrategy is not in 1.3 xsd?

### ISSUE THREAD

**Issue by xoxota99** [nifty-gui/nifty-gui#106]
When using imageMode="resize" with the nine-part border thingy, I see messages in the log that the property was converted to renderStrategy="nine-part". So I went and made that change manually in the XML, and while it works fine, my validation fails because renderStrategy isn't part of the 1.3 XSD, even though it's supported. So when will it become a part of the schema?

**Comment by void256** [comment]
Well, I don't know to be honest :)

It would be easy to add but the problem is the version number in the xsd. Changing the xsd without changing the version will probably make people mad (since different versions would exist with the same namespace - not good).

In retrospect the version number was probably a crap idea. A better aproach would be to just state "the version of the xsd that ships with Nifty is the version **this** Nifty uses".

So maybe we should add "imageArea" and "renderStrategy" as optional attributes to the xsd for 1.4 and drop the version number from the namespace.

You cool with that?

**Comment by xoxota99** [comment]
Well, I'm not really current on all of the concerns around the versioning of the schema, but I feel like one guiding principal to keep in mind might be that "if the parser supports it, then it shouldn't fail validation". Whether that means adding some "extension" namespaces or something else, I'm not sure.

**Comment by void256** [comment]
How do you validate the XML against the XSD? Is that somekind of tool? I asked just because I've tried it and added a

```
<image renderStrategy="bla" ...
```

to an image element and validated the XML with a call to Niftys own validateXml() method as well as the XML-Validator integrated into Eclipse. Both seem happy with that additional attribute which actually makes sense since you **are** allowed to add general generic attributes (that Nifty don't know about) to any Nifty element because of this in the XSD:

```
<xs:complexType name="elementType">
  ..
  <xs:anyAttribute processContents="skip" namespace="##any" /> <!-- any attributes are allowed -->
```

So I'm curious why your validation fails?

Besides that I'm considering changing the namespace for Nifty 1.4 to one without the version and just change to a "The XSD that Nifty includes is the correct one for this Nifty version" mindset. It should make adding changes to the Nifty XSD easier. The only drawback is that you'll need to look into the nifty.jar to get at the correct XSD.

**Comment by void256** [comment]
Attribute added to the XSD for Nifty 1.4.
