### ISSUE TITLE
Allow option to set minimum scrollbar thumb size.

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#108]
I need the ability to set a hard limit pixel-wise on how small the scrollbar thumb will get, no matter how many items are added to a listbox.

Currently it seems to have some kind of default limit, but I can't find any way to change it without rewriting part of niftyGui.

**Comment by void256** [comment]
Nifty uses the initial width (horizontal scrollbars) or the height (vertical scrollbars) of the handle as the minimum size already. If you look at the default style definition for the scrollbars in the nifty-style-black project (nifty-scrollbar-style.xml) you'll find this:

``` xml
  <style id="nifty-vertical-scrollbar#position">
    <attributes filename="scrollbar/scrollbar.png" x="0px" y="0px" width="23px" height="8px" imageMode="sprite-resize:23,23,13,4,15,4,4,4,15,4,15,4,15,4,4" childLayout="center" />
```

So Nifty will use the height attribute (8 px) as the default size for the thumb size.

If you want to change that you could change the width/height in the default style or make your own copy.

I'll leave this ticket open since I agree that this would be a nice feature to have available from Java. I just wanted to explain how this currently works.

**Comment by ghost** [comment]
Ok, you're talking about the initial size of the handle. I already have that set. The initial size is working fine. What happens though, is after adding a lot of items to the listbox, the scrollbar handle goes below this initial height. I want to clamp it so that the smallest it will ever get, no matter how many items are added to the listbox, is the height variable that you just mentioned.

Also keep in mind that my scrollbar handle "height" is set to 22px. The handle shrinks well below this as the number of listbox items increases. I think maybe you can't see the problem because the scrollbar handle probably never shrinks below the default of 8px that is currently being used (that's a pretty small value anyway).

**Comment by void256** [comment]
Well, I did understand you and I was actually talking about the minimal size :smile:

I did look at the code and Nifty really uses the initial size **as** the minimal size for the scrollbar handle. Since Nifty always resizes the handle according to the scrollbar configuration (worldMax, wordPageSize, position and so on) there is no need for an initial size. Therefore Nifty uses the initial size as the minimal size.

The "8px" you're seeing is exactly the initial height given in the example above - which I've copied from the standard style (Nifty 1.3.x). Btw: I've fixed the broken XML in the comment above too.

In fact I've changed the 8px to 23px in the standard style definition and it works for me. The scrollbar handle stops at a height of 23px and is not resized any further.

When and where do you set the height of the handle to 22px? The initial height of the scrollbar handle is read at the time the ScrollbarControl.bind() method is called. If you set it at a later time it will not be used, I'm afraid. Maybe that is the problem?

If not and you're sure that you set it before creating the Scrollbar control I'd ask you to provide a SSCCE for me to reproduce. Because it seems to work for me.

**Comment by ghost** [comment]
Ok, sorry I did not mean to sound condescending. I will see about an SSCCE.
Thanks for the reply.

**Comment by void256** [comment]
I didn't "read" any "tone" into your message. So, no worries.

Just to make sure I've not overlooked something I've added 1000 entries to the standard controls listbox example/showcase demo thing (the one with the ying/yang in the beginning). This Listbox only diplays 4 items out of the 1000. I've used a height of 22px and when the handle reaches these 22px it stays there. So this looks pretty good.

I've changed the default style directly so I'm pretty sure the issue depends on more or less exactly the way you change that parameter (or your rendering system maybe). I'll wait for your sscce then!

**Comment by ghost** [comment]
I solved it! It wasn't nifty after all ;). I wasn't counting the pixels correctly. There was actually an optical illusion going on that made the scrollbar handle appear to not be square (22x22 px).

My custom handle sprite has a 2px black border on the top and bottom, whereas the sprites for the scrollbar arrow buttons (22x22 px) don't have these borders. So when comparing the scrollbar handle visually to the arrow buttons, it had the effect of making the handle look rectangular (i.e., smaller in height than 22px).

I was so certain that it was smaller than 22 pixels in height, until I took screenshots, blew them up, and actually counted pixel-for-pixel.

All I had to do to fix it was make the scrollbar handle minimum height 26px, so the inner part (the part inside the black borders) would be square (22x22 px).

Sorry for being quick to blame nifty! Anyway, keep up the great work. Your library is awesome, and always growing in awesomeness. :D

**Comment by void256** [comment]
Great you found it! :smile:
