### ISSUE TITLE
Assigning an id from a custom attribute to a control inside a custom control.

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#109]
Using version 1.3.0. The code:

``` xml
    <controlDefinition name="text_input">
            <panel childLayout="vertical" height="50" width="100%" align="center">
                <panel childLayout="horizontal" width= "300" align="center" height="190">
                    <control name="label" text="$label" height="40" width="100"></control>
                    <control id="$id" name="textfield" width="200px" height="40" backgroundColor="#aaaf"></control>
                </panel>
            </panel>
        </controlDefinition>
```

This control is used this way:

``` xml
    <control name="text_input" id="map_width"  label="Map width: "></control>
```

In manual it's said that the contents will be replaced with the actual contents of what is inside of controlDefinition, instead when running the example and trying to type some text into the custom control's definition - a null pointer exception occurs. 

It seems that the id attributes are somehow in conflict.

**Comment by void256** [comment]
Well, there are really two issues here:

**FIRST Problem**

Don't use Nifty attribute names for your own parameter names! This will probably always f_ck something up really bad :grinning: So it would be best to use some prefix or suffix, something like "$myId" or "$parameterId" or "$internalId" just *_NOT*\* only "$id" or "$width" or "$name" for that matter. Otherwise Nifty doesn't know which one to apply (your parameter attribute or the regular Nifty attribute with the same name) and since parameters can be resolved over many levels of elements you'll get yourself into trouble very easily.

For instance in your example if you would forget the id="map_width" part when using your "text_input" control there still would be an id available eventually from somewhere up in the hierachy. Something like:

``` xml
  <layer id="layer" ...
    <control name="text_input"  label="Map width: " />
```

would apply the id "layer" to your control because of the way parameters are resolved! And **that** is nothing you want to happen, ever. really. :wink: 

Of course Nifty should probably tell you if it encounters a $-value that looks like a standard attribute but that is not so easy as it might sound at first. The default controls use their very own set of parameters as well so it's not trivial to know all the possible parameter names for each element. I think it might be possible but that's nothing I'd like to think about right now to be honest.

Everything will be better in Nifty 2.0 :wink: eventually.

**SECOND Problem**

There was an issue (see the git commit in the comment above) that Nifty internally resolved all the ids first and then applied the parameters. What I mean is that when you apply an control with some id - the regular Nifty build-in id attribute - this id will be used as a parent id for all of its child element from the controlDefinition. Nifty will simply combine that parent id with the id of a child element forming a new id. So for example, if you have some element inside of your controlDefinition with id="stuff" and you later create a control from this controlDefinition and you give that control the id="my-control" the internal id of the element inside the applied/resolved control will be "my-control#stuff".

I hope that makes sense to you and my explanation is not too bad :sunglasses: 

The problem only occured when you replace ids inside the controlDefinition with the parameter mechanism since Nifty originally resolved all of the ids **before** the parameter replacement happend. So your real id never appeared inside of the control which caused the text-field control to not have an id and therefore couldn't be found later causing the NPE you saw.

The commit above will fix that by replacing parameters now **before** the ids resolving stuff is happening.

Your example appears to work for me now after I've applied the patch above.

Can you eventually try it with a latest 1.3.3-SNAPSHOT build and confirm that this really fixes the issue?

**Comment by ghost** [comment]
Thank You, this explains the issue. Actually the problem on my side was that I had no idea how to access an inner control of a custom control using Screen::findNiftyControl. Now I see i can do it by passing something like       

``` JAVA
    screen.findNiftyControl("map_height#textfield", TextField.class);
```

in case my custom control definition is like:

``` XML
    <controlDefinition name="text_input" controller="gui.TextInput">
        <panel childLayout="vertical" height="50" width="100%" align="center">
            <panel childLayout="horizontal" width= "300" align="center" height="190">
                <control name="label" text="$label" height="40" width="100"></control>
                <control id="#textfield" name="textfield" width="200px" height="40" backgroundColor="#aaaf"></control>
            </panel>
        </panel>
    </controlDefinition>
```

and it works.

I really can't easily check the patch because I'm using Nifty integrated with JME and it seems not simple to change the version (when tried with NGUI 1.3.2 error occured). 
If it works for You - I think the issue can be closed.

I would also suggest to explicitly mention about this in manual  - those are usefull informations.
:smiley:

**Comment by void256** [comment]
The problem with mentioning stuff in the manual is ... you don't know what is really important beforehand :smile: You only know it afterwards when people miss some information. But yes, if I'll do a new revision of the book I should really mention these points! :smiley:

Well, you could try to use a very recent nightly build of jme3 since it contains a Nifty 1.3.3-SNAPSHOT build already. So this version should be compatible with the very latest Nifty nightly build. The Nifty version that jme3 contains is updated manually so it's not always the very latest but I've updated it one or two weeks ago so it should be pretty recent :smile: 

Thanks for the reply!

I'll close this issue now.
