### ISSUE TITLE
Nifty 1.3.0 suppressess exceptions

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#116]
The NIfty GUI doesn't pass the exceptions thrown in client code. It seem the library is "eating" all errors and exceptions and there is no way to terminate an application by throwing an exception. 
I can't see stack trace of my errors, and simply things that are supposed to be responded by user interaction are caught by NGUI and nothing happens. 
Is there any solution to this?

**Comment by void256** [comment]
Do you refer to:
- The `<interact onClick="" ... >` way to call client code or
- The EventBus @NiftyEventSubscriber events?

For the old-style "interact" method calls the NiftyMethodInvoker does indeed catch all Exceptions and simply logs them as warnings:

``` java
  private Object callMethod(final Object targetObject, final Method method, final Object[] invokeParameters) {
    try {
...
    } catch (RuntimeException e) {
      log.warning("RuntimeException: " + e.toString());
      logException(e);
      return null;
    } catch (Exception e) {
      log.warning("Exception: " + e.toString());
      logException(e);
      return null;
    }
  }
```

The idea here was that client code that basically "explodes" :smile: will not crash the whole application. Terminating the application by throwing a RuntimeException is therefore currently not possible.

I don't refuse to change this though. I'm just not sure what is more important here: Don't let the GUI crash (or make sure that your client code does handle all Exceptions to prevent that) or simply don't handle - especially the RuntimeException - anymore which would lead to your expected behavior. Opinions?

As a workaround you could throw a Throwable through but I don't like that neither...

If you refered to an Exception thrown in some EventBus Subscriber then the EventBus project used actually catched all Throwables and only logs them. As far as I see there is nothing one can configure to change that behaviour.

**Comment by ghost** [comment]
I refer to <interact onClick=""> issue . Exactly the issue that RuntimeExceptions are catched by Nifty. 
In my opinion this behaviour is not appropriate to the "raw" code handling, where RuntimeExceptions terminates a thread, and a stack trace of an error is written.  
The problem is, that - usually when I click on an element with <interact onClick=""> my buggy code that is to be executed by this event doesn't throw information about what is wrong. Before I found a workaround (by re-throwing the runtime exception in "try - catch" block) it was very frustrating, cause I was unable to find out what's wrong (cause simply nothing happened). 
I'm not sure about Your opinion, but for example - Swing GUI throws such errors.

I think that those errors should be kept, as they emphasize what is wrong and saves client from searching potentiall errors, which in the console, where there are sometimes - a thousand of lines - are hard to find. 

I would like also to suggest the same behaviour for errors in xml files. For example forgetting to specify, or specyfying wrong controller in <screen> element doesn't terminate the thread and the warning could be easily overlooked.

This maybe not the case for someone who knows these things, but for a beginner like me it was hard time to figure what was wrong.

**Comment by toolforger** [comment]
Am 12.05.2013 21:32, schrieb void256:

> The idea here was that client code that basically "explodes" :smile:
> will not crash the whole application. Terminating the application by
> throwing a RuntimeException is therefore currently not possible.

Best practice for a software layer that does not know what to do about a 
given error situation is throwing an exception and defer to higher 
software levels to deal with the situation.
If the error situation is an unexpected exception, let that exception 
bubble up the call stack. If it's a checked exception, wrap it in a 
RuntimeException (throw new RuntimeException(caughtException)).

Applications must be able to deal with unexpected exceptions anyway.
In games, this usually means logging to stdout, or (in a more 
sophisticated software) mailing the exception to the devs.

**Comment by ghost** [comment]
Yes, but I think that those exceptions should be catched by developer not Nifty itself.

**Comment by philipwhiuk** [comment]
If it were possible to replace the `NiftyMethodInvoker` with a different one that could override the current behaviour it wouldn't have a problem.

I have a solution:

``` java
static class NiftyMethodInvokerFactoryFactory {
     static NiftyMethodInvokerFactory factory = new DefaultNiftyMethodInvokerFactory();
     static void setFactory(NiftyMethodInvokerFactory factory) {
            this.factory = factory;
     }
     static NiftyMethodInvokerFactory getFactory() {
            return factory;
     }
}
interface NiftyMethodInvokerFactory {
     NiftyMethodInvoker getInvoker(final Nifty nifty, final Object ... controlController);
}
class DefaultNiftyMethodInvokerFactory {
     getInvoker(final Nifty nifty, final Object ... controlController) {
          return new DefaultNiftyMethodInvoker(nifty,controlController);
     }
}
interface NiftyMethodInvoker {
    boolean invoke(Object ... invokeParametersParam);
    void performInvoke(final Object ... invokeParametersParam);
}
class DefaultNiftyMethodInvoker implements NiftyMethodInvoke{
    //Existing NiftyMethodInvoker stuff
}
```

When one is required you'd call

``` java
NiftyMethodInvokerFactoryFactory.getFactory().getInvoker(nifty, args);
```

To overide the default behaviour you'd do:

``` java
NiftyMethodInvokerFactoryFactory.setFactory(new NiftyMethodInvokerFactory {
       getInvoker(final Nifty nifty, final Object ... controlController) {
          return new MyNiftyMethodInvoker(nifty,controlController) {
                //Override invoke() and performInvoke()
          }
     }
}
```

**Comment by void256** [comment]
Changing the whole NiftyMethodInvoker is quite some brute force solution to that issue :smile: 

What about adding a system property to configure this behaviour? Or maybe a setter on the main Nifty instance?

Something like "-Dnifty.NiftyMethodInvoker.donotcatchexceptions=true" or "nifty.setNiftyMethodInvokerDontCatchExceptions(true)" so that the Nifty user can decide the default behauviour?

**Comment by relu91** [comment]
yes , I think that a property is more appropriated . So a dev could take it to true while is developing and set it false when he distributes his application . With this, the dev is fine and also the final distributed app will work in a safe environment . Maybe you can set it as default to true.... :smile: . About the name I think it's better for reasons below to call it DebugMode .

**Comment by toolforger** [comment]
One can do it with a property, yes.
However, it's already done by the logger framework; no need to reinvent the wheel here.
Just do it like this:

```
try {
  // Call back into application code
} catch (Throwable t) {
  logger.error("Unhandled exception", t);
}
```
