### ISSUE TITLE
Text on colorless panels look strange when overlapping geometry

### ISSUE THREAD

**Issue by Crushy** [nifty-gui/nifty-gui#120]
This test was done using the latest snapshots for LWJGL-renderer and nifty (    nifty-lwjgl-renderer-1.3.3-20130504.140852-24.jar and nifty-1.3.3-20130504.140311-25.jar respectively)

Both of the screenshots have a blueish glClearColor.

![problem](https://f.cloud.github.com/assets/4438626/507305/d62d2b4a-bd6c-11e2-887f-ca9b91a30c10.png)

![issue](https://f.cloud.github.com/assets/4438626/507306/d6475e2a-bd6c-11e2-8883-15dc4e6b154f.png)

Example code (tried to trim it down as best I could but unfortunately the pipeline takes up most of it):
http://pastebin.com/mDM1qnnB

Resources folder:
https://dl.dropboxusercontent.com/u/12755420/resources.7z

**Comment by void256** [comment]
I think you'll have to enable blending before calling niftys render() method? Changing your code a bit:

``` java
...
try {
          while (!this.finished) {
                GL11.glClear(GL11.GL_COLOR_BUFFER_BIT | GL11.GL_DEPTH_BUFFER_BIT);

                if (Display.isCloseRequested() || Keyboard.isKeyDown(Keyboard.KEY_ESCAPE)) {
                    this.finished = true;
                }

                // update Nifty
                if (nifty.update()) {
                    finished = true;
                }

                // ### enable blending
               glEnable(GL_BLEND);

                // render Nifty (we don't want it to glclear the screen)
                nifty.render(false);

                // ### disable blending
                glDisable(GL_BLEND);

                render();

                Display.sync(FRAME_RATE);
                Display.update();               
            }
        }
        catch (Exception e) {
            e.printStackTrace(System.out);
        }
```

Currently, the core renderer kinda assumes that blending is enabled. The actual blendFunc() will be changed by Nifty. You don't have to provide it but don't assume anything after the nifty.render() method has been called :)

And you are right, the [stackoverflow comment](http://stackoverflow.com/questions/13408777/nifty-gui-control-prevents-the-rest-of-my-application-from-rendering/13425866#13425866) I referred to earlier will not work for core profile since there is no glPushAttrib() anymore :/

Hmm, I think we'll need to change the Nifty core profile renderer so that it sets all states it requires by itself. At the moment that is only GL_BLEND but it's kinda tricky since you - the caller - does not know what is required. I think I'll have to rethink the way the state managment works for core profile a bit. Thanks for pointing that out :wink:

I couldn't try it with your example code though. The "SSCCEgui.xml" is missing unfortunately. I've tried running it with some simple replacement xml-file but your code still gives me these errors:

```
OpenGL version: 3.2 ATI-1.6.37
Loading shader: resources/shaders/verysimple.vert
Loading shader: resources/shaders/verysimple.frag
16.05.2013 01:30:13 SSCCE main
SCHWERWIEGEND: null
java.lang.RuntimeException: Program validation failure: Validation Failed: No vertex array object bound.

    at SSCCE$Program.<init>(SSCCE.java:284)
    at SSCCE.buildShaders(SSCCE.java:335)
    at SSCCE.initGL(SSCCE.java:342)
    at SSCCE.init(SSCCE.java:327)
    at SSCCE.main(SSCCE.java:150)
16.05.2013 01:30:13 de.lessvoid.nifty.renderer.lwjgl.render.batch.core.CoreShader getUniform
INFO: [4] glUniformLocation for [uModelViewProjectionMatrix] = [1]
16.05.2013 01:30:13 de.lessvoid.nifty.renderer.lwjgl.render.batch.core.CoreShader getUniform
INFO: [4] glUniformLocation for [uTex] = [0]
java.lang.NullPointerException
    at SSCCE.render(SSCCE.java:355)
    at SSCCE.run(SSCCE.java:201)
    at SSCCE.main(SSCCE.java:155)
```

I'm not sure whats going on.

I don't know if you have seen this example code for 1.3: https://github.com/void256/nifty-gui/blob/1.3/nifty-examples/src/main/java/de/lessvoid/nifty/examples/defaultcontrols/ControlsDemo.java 

It is using the core profile renderer too and will setup the states correctly. Although I did not see any other states besides enabling GL_BLEND there.

The font files in your resources folder look good (e.g. they have alpha). I think enabling blending is the only thing thats missing. Nifty should be able to render the fonts with alpha transparency on top of your rendered background! I can't think of anything else that would prevent it.

**Comment by Crushy** [comment]
I was going to mention just now that I forgot to include the GLBlend (it didn't change much in that particular example). I'm going to investigate these errors and examples in a few hours as soon as I get home.

EDIT: I have some more spare time now so I'll add some more detail: the upper screenshot was taken with blending disabled on the example I've given. The lower one is my current project, with blending enabled. Enabling blending on the example displays the text exactly like the lower one (the artifacts around the font start using glClearColor instead of black and the text no longer overlaps slightly). Anyway, like I said more info when I get home. Thanks for all the help so far.

**Comment by Crushy** [comment]
New version (tested on ATI cards). This one uses gl_blend and the depth buffer (the text would be obscured by the triangle if I didn't enable it)
http://pastebin.com/ZcDKyeeR

SSCCEgui.xml
http://pastebin.com/MGPfcyEr

I already looked through all the examples I've found and I haven't seen one which demonstrates the gui and custom geometry. I've seen a couple of games made with your gui but haven't had the time to look at them yet, and they don't seem to overlay text directly on top of geometry.

Hope this helps.

**Comment by void256** [comment]
Is there are reason why you first render Nifty and then your geometry? Shouldn't it be the other way around?

Like so:

``` java
     // render your stuff
     render();

     // render Nifty
     // since Nifty currently doesn't know or care about z we'll disable the DEPTH_TEST
     GL11.glDisable(GL11.GL_DEPTH_TEST);
     nifty.render(false); 
     GL11.glEnable(GL11.GL_DEPTH_TEST);
```

This worked for me:

![bildschirmfoto 2013-05-17 um 01 12 36](https://f.cloud.github.com/assets/1095704/515636/3dbc9ee6-be7e-11e2-930a-50575ceed80a.png)

But I'm curious. Did you do that on purpose? And if so, why?

And the problem why your original program (and the updated version as well) crashed for me, is that OS X takes the OpenGL 3.2 spec more seriously as your Windows/Linux driver does.

In Section "E.2.2 Removed Features" the OpenGL 3.2 (Core Profile) spec says:

> Client vertex and index arrays - all vertex array attribute and element array
> index pointers must refer to buffer objects. The default vertex array object
> (the name zero) is also deprecated. Calling VertexAttribPointer when no
> buffer object or no vertex array object is bound will generate an INVALID_-
> OPERATION error, as will calling any array drawing command when no vertex
> array object is bound.

In other words: To render something successful in OpenGL 3.2 core profile you'll need a bound vertex array object.

First you're calling buildShaders() which creates/validates the shader program and after that you call prepareDrawingThings() which will create and initialize the VAO/VBO.

Creating the shaders and the program as well as linking them _IS_ allowed before creating/binding VAO/VBO but you're also calling glValidateProgram() in the constructor of your Program class. And glValidateProgram() checks _every_ state involved to make sure a successful drawing call can be performed using this program at the time you call glValidateProgram(). This will check for a bound vertex array object on Mac OS X (which is correct IMHO). But at the time you call glValidateProgram() there is not yet a VAO created and therefore this call fails.

You should move the glValidateProgram() call to a later time - when you have a bound VAO. Or you can remove it completely since it's only a tool to aid in development and actually the [reference doc](http://www.opengl.org/sdk/docs/man/xhtml/glValidateProgram.xml) for it says:

> This function is typically useful only during application development.

**Comment by Crushy** [comment]
Ah! That indeed fixed it.

I think I read in a couple of places that nifty should render BEFORE the rest of the program so I never gave it second thought. The nifty manual even uses this pseudocode:

``` java
// render and update Nifty
boolean done = false;
while (!done) {
    // update Nifty
    if (nifty.update()) {
        done = true;
    }

    // render Nifty
    nifty.render(true);

    // render other stuff, call LWJGL Display.update() and so on
}
```

As for the glValidateProgram call, thank you and sorry about not noticing that issue. I've just recently started using openGL 3.2 and I'm still learning some things as I go. It probably doesn't help that some of the better tutorials have bugs. 

Funny thing I noticed: It seems to be the level of adherence to the spec goes something like: Mac > AMD > Nvidia. I once fed a wrong texture index to the shader on an Nvidia GPU (something along the lines of 523 instead of 1) and it happily rendered the correct texture 0_0'

**Comment by void256** [comment]
Ah, nice! :smile: I see!

Sorry for that example in the manual though. You're right, it's indeed a bit misleading. I should add a second, similar comment before the nifty.render() call. The example was meant to illustrate that Nifty does not necessarily take over all of your screen but that you're able to render other stuff behind or in front of it when you have to.

You might want to take a look at that other project of mine: https://github.com/void256/lwjgl-coregl too. It's just a couple of helper classes/methods to make life with the core profile easier. It's a very thin wrapper around the boiler plate code you sometimes need to write without abstracting too much. I'll use this project when I quickly want to test out stuff and the Nifty batched core profile renderer uses these classes as well. <shameless-plug-off> :wink: 

I'll close this issue for now! Keep my updated on your progress! :smile:
