### ISSUE TITLE
JoglRenderImage throws exception when trying to bind texture

### ISSUE THREAD

**Issue by jcstier** [nifty-gui/nifty-gui#123]
I'm using the Jogl renderer and when I try to dynamically add a new image to the ui it throws: 
May 21, 2013 5:14:08 PM de.lessvoid.nifty.renderer.jogl.render.JoglRenderImage createTexture
SEVERE: GLException: Timer-1: No OpenGL context current on this thread

I'm adding the new panel and image from a timer thread.  The debugger throws an exception on  JoglRenderImage:89  where it's trying to get a handle to the GLContext.  The call to get current throws the above exception.  Is there a different way to load textures?... maybe a way that doesn't require immediate mode calls?
I have a test app that demonstrates this if you want to see it.

**Comment by wmborelli** [comment]
I'm having the same issue. I'm loading imagery (from my filesystem) from a weld bean and I get the "No OpenGL context current on this thread" Exception. I'm pretty sure the weld bean is in its own thread. I've come across this using the Creator and Builder methods. The only thing that appears is a white box in place of my image(s).

My app starts and pulls a set of images from my filesystem and attempts to display the images in panels (a window). Images should be able to be added or removed from the directories on my filesystem. When a window holding 1 or more images is hidden its content is destroyed and then recreated when shown. 
If I have the images on my filesystem at startup and I add those images to the panels when bind() is called then it displays the images that already exist on the filesystem just fine. If you add any images to the filesystem, and the panel is hidden and then attempts to show the just added image(s), then a white box appears.
If I have images on my filesystem at startup and I add those images to the panels on show then it displays a white box in place of the image.
If I use an image when bind() is first called and then again later then the image is displayed just fine and the exception mentioned above is not displayed.
If I use an image in xml, destroy the layer it is shown in programmatically, and then use that same image again later on then it displays just fine.
The main point is: adding a new image to the filesystem and attempting to show it results in a white box being shown and Exception being thrown.

**Comment by void256** [comment]
This is not a Nifty or JOGL problem. Instead it's a general "Multithreaded OpenGL" issue. The message:

``` java
SEVERE: GLException: Timer-1: No OpenGL context current on this thread
```

just means that there is no OpenGL context associated with the thread that tries to load the image resources.

Nifty currently does not support (or know) about different threads. So at the moment it is up to you to make sure that all OpenGL calls (and loading an image ultimately ends up with a call to glTexImage() to upload the texture data to GL) are made from the thread that created OpenGL and/or Nifty.

That being said, it might be possible to associate a second thread with the OpenGL context. But since I'm no expert in multithreaded OpenGL I don't know what additional steps might be necessary to make that work correctly.

PS: Issue #111 documented a similar issue using the EventBus
