### ISSUE TITLE
Scrollbars never reach their worldMax

### ISSUE THREAD

**Issue by telamon** [nifty-gui/nifty-gui#13]
Hi! Just got into nifty and so far I like it alot!
I've noticed today that the stand-alone scrollbars are somewhat broken.

I did a trace on their values during various user input tests, and i've noticed that 
the maximum value they can reach is clipped to worldMax - worldPageSize
Eg.

```
<control id="surfaceScrollX" worldPageSize="10.0" name="horizontalScrollbar" valign="bottom" align="left" width="95%" height="24px">
```

This scrollbar can never reach a value of 100.0 (default maxWorld) 
It gets clamped to 90.0;
If I were to change worldPageSize to 1.0 then it progresses to 99.0

I first encountered this behaviour when i was using scrollbars configured to run from 0-1.0 ,
had the exact behaviour, the value never went above 0.9 until i tweaked worldPageSize to 0.01 and now it goes to
0.99

I haven't had time yet to address this issue in my own software, will check it out later.

**Comment by void256** [comment]
I've not checked this yet with the code so bear with me =)

I think this is because it is a scrollbar :-) that is mainly meant to be used to scroll or navigate a window over a larger area. So in this somewhat typical scrollbar situation, I think the current way it works:

> worldMax - worldPageSize

is actually what you would expect.

The logic - at least what I think I was thinking when implementing it :) - was that you would have this virtual "window" or "page" that you "scroll" around using the scrollbar. Where "worldPageSize" represents the size of that window and "worldMax" the size of the document.

So when you imagine that you've scrolled all the way down then in fact the scrollbar value would really be at

> worldMax - worldPageSize

since you are really at this position in the virtual bigger document represented by "worldPageSize".

Does that maybe explain the issue?

**Comment by void256** [comment]
Accidentally closed the issue but reopened it again ... please feel free to comment :)

Maybe what you want is the slider control? I think you can get this to the max value iirc.

**Comment by telamon** [comment]
Ofcourse that explains it.... yes I'm scrolling a virtual space, I just haven't implemented  a hook back to nifty to update the worldPageSize to match my virtual space yet.

Yes you're right i'm currently using  the scrollbar as a slidercontrol due to that fact, my bad, this will resolve it self once i finish my implementation.

Thanks for clearing that up! :)
