### ISSUE TITLE
PlaySound from XML OnClick effect isn't triggered if element becomes invisible

### ISSUE THREAD

**Issue by arankin-irl** [nifty-gui/nifty-gui#145]
When registering a playSound effect on a control, that sound should play when the event is triggered. Instead, it seems to be played after any event subscribers are notified. If the control element is then set to invisible in the event subscriber, the sound is not played. It does appear to play at some point afterwards, if the element becomes visible again.

Here is a small example to reproduce:

Register a sound effect, and tie it to the onClick of a button:

``` xml
<registerSound id="clickSound" filename="./sounds/click.wav"/>
...
<control id="soundButton" name="button"  childLayout="center" label="PlaySound">
    <effect>
        <onClick name="playSound" sound="clickSound"/>
    </effect>
</control>
```

Add an event subscriber:

``` java
    @NiftyEventSubscriber(id =  "soundButton")
    public void soundButtonClicked(final String id, final ButtonClickedEvent event) {
        event.getButton().getElement().setVisible(false);
    }
```

When clicking the button, no sound will play. If you instead use event.getButton().setEnabled(false), the sound will play correctly.

The workaround that I'm currently using is to play the sound from the method, instead of the XML:

``` java
getNifty().getSoundSystem().getSound("clickSound").play()
```

Thought I would let you know, since the behaviour seems a bit odd.

**Comment by void256** [comment]
Well, at the moment hiding an element will make all effects attached to that element stop and this includes onClick effects as well. Currently the only exceptions to this are "neverStopRendering=true" effects.

Since you can really do anything in an effect I think stopping all effects when the element is hidden is a reasonable behaviour even though I agree that it is irritating in the case you mentioned.
