### ISSUE TITLE
I cant see any writtens

### ISSUE THREAD

**Issue by elect86** [nifty-gui/nifty-gui#167]
I am following the manual 1.3.2 and I am trying to get working the example with different texts in different positions, but it doesnt work

http://pastebin.com/ixDg63ZE

I cant see any writtens actually

![b](https://f.cloud.github.com/assets/5020626/1520190/a3dc0bb0-4b75-11e3-9667-7dd22a955234.png)

**Comment by void256** [comment]
You'll need to include the default styles too - somewhere in the beginning of your xml (before the first screen definition):

```
<useStyles filename="nifty-default-styles.xml" />
```

which, unfortunately, the manual covers in a later chapter. In retrospect that specific example should have been rewritten without the use of styles but it was probably lazily :smile: copied from an already existing example.

You can find the complete XML for that example here: https://github.com/void256/nifty-gui/blob/1.3/nifty-examples/src/main/resources/textalign/textalign.xml which I'd suggest for reference.

Without the useStyles Nifty does not know how to use `style="nifty-label"` attributes on the text tags. This way Nifty does not know what font you want to use which results in no text being rendered.

Oh and one additional note: Make sure you have nifty-style-black.jar on your classpath as well (since all the resource and style files are in that jar).

**Comment by ghost** [comment]
@elect86 Your `<nifty>` tag should be like this:
`<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">`

**Comment by ghost** [comment]
@elect86 If you run your application from the command line, you should see warnings logged from Nifty Gui about missing styles. I recommend always testing your application from either the command line or an IDE console where you can see any warnings or errors that are logged. This will make it a lot easier for us (and you) to solve your problems in the future. ;)

**Comment by elect86** [comment]
@void256 no problem, thanks anyway for helping me finding the solution :)

Dont worry about the jars, I basically included all the jars that I found, that one included

@3xp0n3nt why my <nifty> tag should be something like that? If it is explained in the manual just point me there

Ah yeah, you are right, you mean this one?

WARNING: missing font in renderText! could it be that you're using <text> elements without a font or style attribute? in case you've replaced <label> with <text> you're probably missing style='nifty-label' :)

Ps: btw probabily it has nothing to do with any technical side, but since we are here, I exploit it ^^, now I get this crappy writtens, I guess it may depend on the style/size choosen?

![c](https://f.cloud.github.com/assets/5020626/1529742/9e19c97e-4c3d-11e3-8312-7ec42bf87902.png)

**Comment by ghost** [comment]
@elect86 Look on page 16 of nifty-gui-the-manual-1.3.2.pdf. And yes, 
that's the log message related to your problem. Make sure you check 
those next time you have a problem ;)

elect86 wrote:

**Comment by ghost** [comment]
> elect86 commented 11 hours ago
> 
> Ps: btw probabily it has nothing to do with any technical side, but since we are here, I exploit it ^^, now I get this crappy writtens, I guess it may depend on the style/size choosen?

Show us **teh codez** if you want help!

@void might be able to nail this right off, but, just guessing without seeing your code, it could be:
- The text size you specify does not match the text size of the font file you have chosen.
- The path to the font file is incorrect.
- The font file is not in the correct format - are you using a built-in font with .png and .fnt files in the same directory, or are you using some custom font you downloaded / created? There's a specific process for creating custom fonts.

Questions:
- Which RenderDevice implementation are you passing to the Nifty constructor?
- Are there any more log messages?
- Do you have auto scaling enabled?

**Comment by elect86** [comment]
So bro, you wanna teh codez, eh? ^^

Here you go

http://pastebin.com/xMutKFq7

**Comment by void256** [comment]
This paste has been removed! :/

I think @3xp0n3nt has raised some important questions: especially RenderDevice you use? Plain LWJGL? Slick2D? JME? JOGL? BatchRenderDevice or regular? LibGDX?

To me it looks like texturing is disabled when Nifty is trying to render the font or something like blending is configured wrong. Which usually should not happen since Nifty usually enables that correctly in its render() method but something like multitexturing, shaders etc. could all mess this up.

So yes, the code or a SSCCE would be helpful!

**Comment by elect86** [comment]
Cmon dont be mean, dont delete my paste >,>

Btw I am using JoGL, you can find everything here

http://pastebin.com/qgd9THUz

**Comment by void256** [comment]
Thanks for the example! When I run it I see the same odd effect :smile:

But fortunately it's easy to fix. Blending needs to be enabled before calling the nifty.render() method. You can fix it in your example like so:

``` java
...
            @Override
            public void reshape(GLAutoDrawable drawable, int x, int y, int width, int height) {
                GL3 gl3 = drawable.getGL().getGL3();
                gl3.glViewport(x, y, width, height);
                gl3.glEnable(GL.GL_BLEND); // <-- ADD THIS LINE RIGHT HERE
            }
```

Usually Nifty sets all states it needs in the render() method directly but unfortunately the new batched renderer for the core profile did not. Since other RenderDevice implementations do this I'll treat that as a bug and will fix that in a minute. Thanks!

**Comment by elect86** [comment]
Damn, I missed somehow your last replies..

Btw it works like a charm now, thanks and congratulations for your great work!

**Comment by elect86** [comment]
So, going forward with the manual, I get an exception 

Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Resource not found: verdana-smallregular. fnt

at the example at page 34

http://pastebin.com/cWcNMWts

I guess I am missing the verdana font.. right?

**Comment by ghost** [comment]
> elect86 commented 9 hours ago
> So, going forward with the manual, I get an exception
> 
> Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Resource not found: verdana-smallregular. fnt
> 
> at the example at page 34
> 
> http://pastebin.com/cWcNMWts
> 
> I guess I am missing the verdana font.. right?

Either that, or you're not specifying the path to the resource correctly. The path starts relative to the root of the jar (don't start the path with a / or that will start the path relative to the root directory of your local filesystem, which would make your application only work on your computer).

The best way to deal with things like this (assuming you do have that font file) is to [extract the jar](http://www.wikihow.com/Extract-a-JAR-File) and look for the resource inside. So if you extract a jar named `myApp.jar`, it should extract the contents to a folder named `myApp`. Let's say you open the `myApp` folder and look inside. Any files you see inside that folder (that are not inside a subfolder) can be specified directly in Nifty without any path. Now let's say you see a subfolder in there named `myFolder`, and inside `myFolder` is `myFont.fnt`. Then you can specify this resource in Nifty by `myFolder/myFont.fnt`.

Nifty will find the resource because `myFolder` sits at the top level of the jar, and when you don't use a forward slash at the beginning of the path, then the path searches starting from the top level of the jar. The forward slash after `myFolder` is used because forward slashes are patform-independent path separators, so that's the only type of path separator you should use.

Good luck.

**Comment by void256** [comment]
Well, the original issue was solved so I'll close this issue now!
