### ISSUE TITLE
Feature: Generic eventbus provider

### ISSUE THREAD

**Issue by telamon** [nifty-gui/nifty-gui#17]
Hello, I see that nifty has pretty sweet eventbus capabilities and my application requires exactly this type of eventbus service.
The nifty eventbus implementation is very free, I can simply extend my own events with `NiftyEvent` and piggy back onto nifty's eventbus. 

But the only thing that stops me is that I Need access to nifty's event bus _before_ I create a `Nifty`instance (Way before I create an OpenGL window).
So I begun implementing my own eventbus that I can initialize independently of the nifty main object, but right now i'm pretty much just reinventing the wheel.

So my question is, would it be a be feasible to move all Nifty eventbus logic out of the `Nifty` class into a statically accessed singleton.

That way nifty could  be used as an generic Eventbus provider without depending on an complete Nifty Implementation.

What's your thoughts on that?

**Comment by void256** [comment]
Well, Nifty uses the "eventbus" project internally. Sadly it's homepage http://www.eventbus.org is missing in action and it's other homepage seems a bit outdated http://java.net/projects/eventbus   So I don't know it's current state.

BUT all the EventBus stuff that Nifty provides is really just using this project. So actually the EventBus already exists independently from Nifty! There is a private initalizeEventBus() method inside the Nifty class that "creates" this EventService instance internally. Every event that Nifty generates will be routed to this EventService instance.

So in general you can use the EventBus-stuff completely independent from Nifty if you want/need to!

If you really need to use the same EventService that Nifty uses, I think what we need to do is to give you a way to inject an existing EventService into the Nifty instance. Basically you'll need to instantiate the EventService (the initalizeEventBus() method) and give this instance to Nifty. Done.

Would that help you? :)

Please note that we'd only need that stuff if you really need to use the _same_ instance as Nifty does. If this is not necessary you can do whatever you like by directly using the EventBus stuff.

**Comment by telamon** [comment]
Oh great idea! I hadn't thought of that, but what about all the annotation parser bootstrapping in nifty?

Yeah it's really sad that the eventbus page is down, pretty much everything about eventbus is whiped off the face of the internet except for maven repositories. I was in the process of reimplementing that when I found the google "guava" library which also provided an event bus and some other features I liked. I'm gonna try walk down the guava road for now, but if I end up with toomany busses than i bargained for , then I'll try to see if i can get my code to play nice with nifty's eventbus.

I would like to note that my usercase is probably a bit irregular, most nifty users will have created an nifty instance before requiring an eventbus and those people can piggyback upon nifty eventbus freely. My case is that the opengl/nifty frontend is an optional module. So to sum it up I guess i should not try to fix something that is not broken =)

**Comment by void256** [comment]
I've just contacted the original author of the eventbus project and even though he's pretty busy with other things at the moment, he said: "maybe in the summer" ;) so not all hope is lost for the "eventbus" project :)

About annotations and Nifty: There is an EventServiceLocator class inside of the eventbus project which can be used to register EventService instances under a name. Here is the initalizeEventBus() method from the Nifty class:

``` java
  private void initalizeEventBus() throws EventServiceExistsException {
    EventServiceLocator.setEventService("NiftyEventBus", new ThreadSafeEventService());
  }
```

So the whole EventService is registered with the name "NiftyEventBus" and whenever this specific "Nifty" EventService instance is needed (and no Nifty instance is available, like in the NiftyEventAnnotationProcessor helper class) Nifty gets it from the EventServiceLocator like so:

``` java
  private static EventService getEventService() {
    return EventServiceLocator.getEventService("NiftyEventBus");
  }
```

So if you really really really REALLY need to have the "Nifty" Evenbus available before creating the Nifty instance then you could register it yourself with the EventServiceLocator. In that case we just need to modify the initalizeEventBus() method to check if there is already an EventService registered with that name and use it, when it exists.

BUT I think you need to convince me first that this is really required =)

I still have a slight feeling that you might want to use a different EventService (EventBus) instead of the Nifty one ...

**Comment by telamon** [comment]
Yes i came down to the same conclusion, guava worked like charm for my intents.
Closing this issue for now, sorry for spawning wild ideas :D

**Comment by autonull** [comment]
https://www.youtube.com/watch?v=p2IxROXWtb0 niftygui 3d jme
https://github.com/automenta/nifractal had to modify it to support multiple eventbus
and modify the JME 3d nifty example to accept mousepick adapted inputs

**Comment by relu91** [comment]
Hey, that's super cool!!! really great work!! Some time ago I was, indeed wondering if something like what you have done, could be made with nifty-gui and jme3. Do you think that you could sometime integrate your changes with the official nifty-gui and JMe3 ?

**Comment by autonull** [comment]
it's possible! i last used JME when it was version 2 several years ago. let's see what some more experienced JME3 developers think, i'll post in the JME forum.  i would like to know if it's possible to upgrade to nifty gui 1.4 or 2.0 -- though 1.3 is included with JME3 and its the JME example i started with.  1.3 might actually be a good starting point anyway because i want to remove all nifty's XML configuration and replace the component hierarchy with JME nodes like Lemur GUI is trying to do.  here's some older videos of  JME2 experients i'd like to improve on https://www.youtube.com/user/automenta/search?query=spacenet  any suggestions or help appreciated

**Comment by relu91** [comment]
I think that your work is just awesome as it in the video and if you can it should be integrated with 1.4 or even in 1.3.3 but @void256 has the last word here. About your other plans I don't think that nifty will ever drop the xml configuration and also jme core developers are not really interested in an unified gui system... . Anyway let's see what others have to say :+1:  . Good luck!

**Comment by void256** [comment]
>  i would like to know if it's possible to upgrade to nifty gui 1.4 or 2.0

It's possible to update to 1.4. However it will require a bit of work. I've outlined some of the steps necessary in the jme forum here: http://hub.jmonkeyengine.org/forum/topic/integrate-newer-nifty-1-4-or-2-0/#post-293429

As mentioned in that thread it would be best to host a jme3-integration project for Nifty 1.4 in our own github repository because jme3 will probably not update the included Nifty to 1.4 (Edit: for the current, stable jme3 version! maybe in the next version ...) because it's not complete backwards compatible with 1.3. This makes sense and is something I understand.

I think it would be possible to extract the jme3-nifty jar which is the jme3-nifty integration, update it to 1.4 and host it alongside the other projects right here. It shouldn't be very hard to do. It's just a bit of work. Any help for that would be greatly appreciated! :smile:

**Comment by relu91** [comment]
> jme3 will probably not update the included Nifty to 1.4 because it's not complete backwards compatible with 1.3. This makes sense and is something I understand.

I remember that normen also said that in the next major release (3.1) they could break backward compatibility, so later also jme will have 1.4 as default. Sorry can't find where he says that tough.  Anyway for who can't wait your solution is the way to go.

**Comment by void256** [comment]
He said it on the thread I've linked above :smile: and it is the right decision for them of course because they have probably most of the Nifty users and just updating Nifty to 1.4 would really break stuff for these users. So waiting for the next major release of jme to introduce breaking changes is the right decision.

For people that can't wait having a Nifty 1.4 / jme3 adapter jar hosted by us would be best. This would allow Nifty to be used with jme using 1.3 AND 1.4 :wink:

**Comment by autonull** [comment]
http://hub.jmonkeyengine.org/javadoc/com/jme3/export/xml/package-summary.html

not sure why it's necessary to require XML. jme3 imports/exports XML as an optional serialization format for the node tree.  if you have to support XML at least provide a JSON option; libraries like JAXB can generate JSON bindings simultaneously. http://c2.com/cgi/wiki?XmlSucks https://jersey.java.net/documentation/1.18/json.html but it's probably better to just leave serialization for an external module. the maven structure of the 1.4 project already is broken into different modules.

**Comment by relu91** [comment]
Nifty-gui doesn't support  only JME and it wants to be more "cross-library" as it can. So it will never have such a strong dependency with JME. That's why it has different renderers. About XML I meant that nifty-gui has it fundamentals in xml structure and it really a lot of work to broke that dependency in the current versions (1.4 or 1.3) but @void256 is working on the new 2.0 realease and it seems to be more java based. As always if I misunderstand something , @void256 you can correct me.

**Comment by void256** [comment]
@relu91 as always you are spot on! :+1:

**Comment by void256** [comment]
what I don't get is, why we discuss all of that on an already closed off-topic issue :flushed:

**Comment by autonull** [comment]
thanks! ive been studying Lemur GUI also and am experimenting with it and Nifty.. attached a screenshot of the two together.  i put nifty 1.3 and lemur projects source code together in the nifractal repository so they can be compared side by side and see what overlaps.  Lemur's model is closer to the scenegraph but Nifty GUI (or Toneg0d GUI) framebuffer is also useful.  for example, the framebuffer acts as a cache so when its screen doesnt need to update, it's rendering cost is minimal.  maybe if the 2d/3d models were unified, a 3d vector gui could flatten itself into a 2D pixel GUI and re-solidify when interacted with or approached closer, like a level-of-detail strategy. 

thanks for the help so far. yes i didnt want to interrupt anythng by starting this discuss so i thought a closed issue was least intrusive

![spacenet2](https://cloud.githubusercontent.com/assets/157093/3944900/de785d0c-261f-11e4-8505-1d70fef49bd6.jpg)

**Comment by ghost** [comment]
@void256 One idea from reading some of these comments is that it would be nice in nifty 2.0 or possibly earlier, to make nifty even more modular, so that xml support would be an optional pluggable component. Java should be the default. I used to use xml in nifty for everything - now I use java builder because it's so much more flexible - and faster to load. I created all kinds of custom factories for different nifty components, to make my java screen builder classes re-use as much code as possible, and to make them easier to read. I couldn't have done that in xml. It's too bad the nifty-controls module (for example) is xml only.

**Comment by ghost** [comment]
> void256 commented 13 hours ago
> 
> what I don't get is, why we discuss all of that on an already closed off-topic issue :flushed:

Some of the best ideas in the world started on the back of a napkin in some coffee shop ;-).

**Comment by ghost** [comment]
Also, since the eventbus.org project is pretty much dead, eventually we should switch to something like https://github.com/bennidi/mbassador. I've been following that project for a while - it's newer and active, and he has benchmarks demonstrating that it's performance is much better than eventbus.org and even guava's eventbus. I incorporated the eventbus.org event bus into my project for my own purposes after noticing how "nifty" it was... So I use it alongside Nifty's instance, with no problems. But I've been slowly getting wooed by mbassador, so that I might try switching my project over to that in the future.

Oh yeah, check out this awesome performance benchmark:

http://codeblock.engio.net/37/

**Comment by void256** [comment]
> One idea from reading some of these comments is that it would be nice in nifty 2.0 to make nifty even more modular, so that xml support would be an optional pluggable component. 

YES for 2.0 :smile:

> Also, since the eventbus.org project is pretty much dead, eventually we should switch to something like https://github.com/bennidi/mbassador.

YES for 2.0 :smile:

MBassador is pretty "nifty" ... I've used it at my day job and it worked very well for us there.

**Comment by relu91** [comment]
> @void256 One idea from reading some of these comments is that it would be nice in nifty 2.0 or possibly earlier, to make nifty even more modular, so that xml support would be an optional pluggable component. Java should be the default. I used to use xml in nifty for everything - now I use java builder because it's so much more flexible - and faster to load

What about also to add more file format? maybe JSON and binary?. A binary format would be fastest to load and JSON will be usefull in android or mobile applications! :+1: .
