### ISSUE TITLE
Panel rendering issue

### ISSUE THREAD

**Issue by qlambert-pro** [nifty-gui/nifty-gui#216]
Hi,
I am trying to use nifty-gui in a video-game project. I am currently facing a problem, the panels seem not to be rendered, the debug output suggests that they are present but they do not appear on the screen (I made sure to set a visible background color). Moreover, switching on the debug option colored panel do not show any panel. But I am able to render text and change its colors without any problem.

It is very likely my mistake, I was thinking that it might be linked to the state in which openGL is when I render nifty. Is there something along those lines I can check, or specific point I should investigate?

**Comment by ghost** [comment]
Hi, could you please be more specific? Please provide the following info, for starters:
- Nifty Gui version
- rendering system (how you create and pass a RenderDevice to the Nifty instance)
- any OpenGL calls you are directly making outside Nifty Gui
- the actual code for the screen you are trying to render, in xml or java
- set Nifty Gui logging level to at least WARN and provide logging output

**Comment by void256** [comment]
Yes, all that what @3xp0n3nt said would be nice to know @Daiwen :smile: 

Until now Nifty has not been very friendly in documenting what states it changes and/or in saving that state automatically. And that depends on what kind of rendering backend you use and if you're using core profile or the regular render path and so on.

Here is a quick list of interesting states you might need to save on your own, e.g. before the render() call and which you'll need to restore after the render() call:
- GL_CURRENT_PROGRAM
- GL_ACTIVE_TEXTURE
- GL_TEXTURE_BINDING_2D
- GL_BLEND
- GL_BLEND_SRC
- GL_BLEND_DST
- GL_PRIMITIVE_RESTART
- GL_PRIMITIVE_RESTART_INDEX

All of that can be modified by Nifty and depending on the specific renderer eventually even more.

That being said, I've already started in the 1.4 branch to improve the situation and make Nifty more easy to integrate with others so that you don't have to care about these states as well.

Here are the relevant commits:

55ec387576a7172e401ce9d916d774e6e5966068
33ebe69b7b00f1934ad59d59adf44968d9e0c44b

**Comment by qlambert-pro** [comment]
Thank you for you answers, here is a little bit more information:
nifty version is 1.3.3,
I am using lwjgl,
as for openGL calls there are a lot of them the project code is here:
https://github.com/Mathgoat/square-loot/tree/inventory
more specifically the nifty code you might be interested in is here:
https://github.com/Mathgoat/square-loot/blob/inventory/src/game/Game.java#L170
I am looking at the logger and will add the relevant information later.

**Comment by void256** [comment]
Thanks!

Since you use the standard LwjglRenderDevice I think my answer on stackoverflow for a similar question might help you: http://stackoverflow.com/a/13425866 :smile:

PS: This is of course the brute force solution (saving all attributes) and not very smart or super performant but until Nifty fixes this internally it's your best bet.

**Comment by qlambert-pro** [comment]
I am looking into it, I am sorry I haven't found your post before.
EDIT: It seems not be working :-(
EDIT2: Here is the only log output I receive from nifty:
https://gist.github.com/Daiwen/096f88e32478e6116bc6

**Comment by ghost** [comment]
@Daiwen Please show your updated render method with the code @void256 recommended.

**Comment by qlambert-pro** [comment]
Here it is:
https://github.com/Mathgoat/square-loot/blob/inventory/src/game/GameLoop.java#L126

**Comment by void256** [comment]
Well, it looks okay to me.

Are you in glOrtho mode (GL_PROJECTION Matrix) when you call nifty.render() too?

Here is some example code from one of the LWJGL examples that setups OpenGL state for Nifty:

```
        IntBuffer viewportBuffer = BufferUtils.createIntBuffer(4 * 4);
        GL11.glGetInteger(GL11.GL_VIEWPORT, viewportBuffer);
        int viewportWidth = viewportBuffer.get(2);
        int viewportHeight = viewportBuffer.get(3);

        GL11.glMatrixMode(GL11.GL_PROJECTION);
        GL11.glLoadIdentity();
        GL11.glOrtho(0, viewportWidth, viewportHeight, 0, -9999, 9999);

        GL11.glMatrixMode(GL11.GL_MODELVIEW);
        GL11.glLoadIdentity();

        GL11.glDisable(GL11.GL_DEPTH_TEST);
        glEnable(GL11.GL_BLEND);
        GL11.glDisable(GL11.GL_CULL_FACE);

        glEnable(GL11.GL_ALPHA_TEST);
        GL11.glAlphaFunc(GL11.GL_NOTEQUAL, 0);

        GL11.glDisable(GL11.GL_LIGHTING);
        GL11.glDisable(GL11.GL_TEXTURE_2D);

        glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
        glClear(GL11.GL_COLOR_BUFFER_BIT);
        glEnable(GL11.GL_TEXTURE_2D);
```

Not all of it is required - but it renders okay with that setup in place. Can you check if you change one of those or if they are set correctly like in the example above when you call nifty.render() ?

**Comment by ghost** [comment]
@Daiwen In cases like this I would recommend creating an [sscce](http://sscce.org/). Keep stripping down all of your custom game code until you get down to the bare minimum program that is still broken, and then submit that code. Along the way you may even discover what was broken.

**Comment by qlambert-pro** [comment]
Thank you very much for your help!
It was all due to the fact that we chose in our project to enable GL11.GL_CULL_FACE
which obviously resulted in  a conflict with your choice of implementation.

The problem is solved now, thank you again.
