### ISSUE TITLE
[Optimization] Use Trove collections

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#242]
I just recently stumbled over this very "nifty" interface library and are very amazed how much it offers! When I looked through the code while implementing it in one of my projects though, I saw that the normal java HashMaps are getting used.

I for myself, prefer to use the Trove collections, since they can increase the performance by a  lot (at least in comparison to the default java ones).
Would it be possible to use the trove stuff in Nifty as well (well, possible yeah, but would you consider adding it?)

Anyway, Thank you for such a powerful library!

**Comment by ghost** [comment]
I don't really support adding yet another dependency to Nifty for many reasons. Check out [this](http://stackoverflow.com/a/629833/711807) for example. Improving performance in Nifty needs to start with the bottlenecks, and I can promise you that collections are not the bottleneck. I also don't like the idea of making the library more bloated for the sake of what I would consider a micro-optimization.

There's a lot of concerns for adding new dependencies to a library, the largest one being support. The library basically absorbs all the bugs and problems of the dependency, not just the features. What happens if you're gone 3 years from now and the Trove library project becomes dead? Who is going to want to do the work of un-converting all of the code back to standard java collections? Not to mention keeping track of updates, filing bug reports with the developers, etc.

I'm not against adding dependencies per se. But only when absolutely necessary, where the benefits far outweigh the costs.

Obviously, @void256 may feel differently - it's not my library after all.

Edit: Something else I forgot to mention is that I am trying to move Nifty in the direction of supporting Android. The first milestone was integrating it with LibGDX, which is completed. The more dependencies added to Nifty, the more difficult it is in general to achieve that goal. For example, I couldn't find any information on Trove / Android compatibility. (I realize it may seem ironic that I added LibGDX as a new dependency to Nifty, but it adds very significant benefits for users of Nifty, and also for users of LibGDX looking for a GUI library, i.e., the benefits definitely outweigh the costs). It's really boils down to a judgement call, and in this case I don't think it's the best idea.

**Comment by void256** [comment]
I agree with @3xp0n3nt that we should not add new dependencies to Nifty thoughtless or as he said only when the benefits outweigh the costs. trove-3.1a1.jar will add 2,6 MB to the download footprint of Nifty too - when I see that right. Pretty big. Not very good.

So at the moment I would not add it, especially since I can't judge how much we gain by using it. And I agree with @3xp0n3nt that there are probably other bottlenecks besides the standard java collections.

**Comment by spaceemotion** [comment]
Thanks for the very constructive criticism ;)

I know that trove doesn't make that much of a difference, but I wouldn't have thought that trove is so big either. I don't really think that trove would just drop, even if it would, I would still work (I haven't noticed any bugs so far and I've been using it for over a year now).

I guess this can be closed then ;)
