### ISSUE TITLE
How to work with double clicks in Nifty 1.4?

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#247]
In Nifty 1.4, two quick onClick()-events seem to be compressed into a single one, which is counterproductive for a doubleclick-routine I made for a special element (in the method that was triggered by an onClick-interact, it checked for the interval between two calls with the current system time (millis) and acted correspondingly), which worked in 1.3.2, but doesn't any more by now. What's the new way to catch a double click's attention?

**Comment by spaceemotion** [comment]
Try to have a look at the `MouseMultiClickEvent`.

**Comment by relu91** [comment]
Hi, I made the multiclick support for nifty-gui as @spaceemotion said you must use MouseMultiClickEvent now. 

> In Nifty 1.4, two quick onClick()-events seem to be compressed into a single one

Actually nifty-gu now generate only one onClickevent when you try to make a double click since the others will fire a MouseMultiClickEvent. You can find any info about implementation in #53 . You can tweak the time of multiclick using "MULTI_CLICK_TIME" properties, you just need to set a value in millisecond to set how much nifty should wait after the first click to generate an other SingleClick event. If you have some other doubts just ask :smile:

**Comment by HariboTer** [comment]
I need to get the corresponding click event without using EventBus. Currently I have the "precedence case of problem" set up like this:

```
        PanelBuilder panelBuilder = new PanelBuilder();
        panelBuilder.childLayoutHorizontal();
        panelBuilder.style(fileStyle);
        panelBuilder.controller(new FileBundle());
        panelBuilder.interactOnClick("fileSelected()");
```

interactOnClick doesn't deliver double click events to me any more, and I couldn't find an "interactOnMouseMultiClick(...)" for it...

**Comment by relu91** [comment]
Oh man I forgot to add it in the builder stuff... :sob: sorry about that. To workaround get the element form the created panel and then retrieve its ElementInteraction instance. From that get ElementInteractionClickHandler and set your method using this : 

  public void setOnMultiClickMethod(final NiftyMethodInvoker onMultiClickMethod)

sorry for that , I'll update the builders as soon as I can!

**Comment by HariboTer** [comment]
With a bit of anonymous overloading on the NiftyMethodInvoker I got it working again (it even seems to be smoother than before^^), thanks for your help! :-)

**Comment by relu91** [comment]
Oh well :D I've just created a pull request with the multiclick support also for builders! :smile:
