### ISSUE TITLE
Nifty-GUI Tutorials not working

### ISSUE THREAD

**Issue by gterminator** [nifty-gui/nifty-gui#254]
Hi,
i tried all nifty XML Tutorials on the Web. Means all XMLs like that are invalid:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://
www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://niftygui.
sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
<screen id="start">
<layer childLayout="center">
<text font="aurulent-sans-16.fnt" color="#ffff"
text="Hello World!" />
</layer>
</screen>
</nifty>
```

The only one who does not give me a Validation Error was:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/void256/nifty-gui/1.3/nifty-core/src/main/resources/nifty-1.3.xsd https://raw.githubusercontent.com/void256/nifty-gui/1.3/nifty-core/src/main/resources/nifty-1.3.xsd">
   <screen id="start">
      <layer childLayout="center">
         <text font="aurulent-sans-16.fnt" color="#ffff"
      text="Hello World!" />
      </layer>
   </screen>
</nifty>
```

but this one didnt work too. Can somebody give me a clear tutorial? I tried it with libs 1.3 and 1.4

**Comment by void256** [comment]
You might want to fix your post because it doesn't show the XML ...

Then you might want to read this: http://nifty-gui.lessvoid.com/?page_id=579

And finally you should realize that the XSD definition in the XML is - at least for Nifty - an optional feature that is only there to support you in writing valid XML. Nifty itself does not require the XSD schema definition as a part of the XML. If you use the `method nifty.validateXml()` then Nifty will automatically validate the XML with the XSD that ships with Nifty regardless of the XSD definition in the XML-file itself.

**Comment by void256** [comment]
@bgroenks96 Why did you label that as "bug fix"? o_O I don't see any bug in this issue ... further more I've explained that the only valid XSD is the one that ships with Nifty. That being said I think all XML's in the nifty-examples project can be used as working examples.

I'll close this issue now. If that was a mistake and I've missed something please reopen it with some explanation. Thanks!

**Comment by bgroenks96** [comment]
I have no idea? :/
