### ISSUE TITLE
Custom OpenGL rendering with effects in a batched renderer

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#263]
Hey, can it be that the batched renderer does its thing after the effects got rendered. While this is not a bad idea, I would like to be able to do custom OpenGL calls in a custom element effect.

In my code I currently have an image overlaying my custom rendered code, whereas I want to have the image below, and then my effect drawing the custom OpenGL things.

I even tried to add a new custom layer, and thus trying to force a new batch to be rendered - no success either.

Is there any other solution or workaround for this? Thanks in advance!

**Comment by ghost** [comment]
You need to be more specific about what you're trying to do. Show the code?

You can't "force" a new batch to be rendered; each batch contains a certain amount of vertex data - layers are a high level abstraction that don't exist in the batching code. However, the vertex data is submitted in a back-to-front order, resulting in the top layer being drawn last. Therefore, if you order your layers properly, anything that is of Nifty Gui will be rendered in the correct order.

The problem is when you access OpenGL directly, you are bypassing Nifty Gui's rendering system completely. It sounds like you're saying you want two incompatible ideas: you want to use custom OpenGL code that Nifty Gui will recognize as being part of the UI and incorporate into its own rendering system, such as sandwiching custom OpenGL rendering between two Nifty layer elements.

The way Nifty Gui is designed is that custom OpenGL rendering is supposed to be a separate system from Nifty - you either render _everything_ in Nifty together, before or after your custom OpenGL code (which would be like a game map / level, for example). When you say you're trying to mix custom OpenGL rendering code **_within**_ Nifty, that's not really supported. Sure, no one's stopping you, but it's probably going to result in situations exactly like this one...

You shouldn't be thinking about "forcing batches to be rendered" either. That is implementation-dependent thinking. What if Nifty Gui completely changes the way it interacts with OpenGL in the future? You can't build a stable app on unstable assumptions, so please, don't do this, for your own sanity ;-).

You'll notice, if you look at the source code of all the effects already implemented in Nifty Gui, none of them use OpenGL. That wouldn't make any sense. Those effects should work even if Nifty switched to DirectX (God forbid ;-)). The effects work by making calls on the Nifty instance, the current Screen instance, layers, elements, etc, and even the NiftyRenderEngine (which is still a pretty high level abstraction). My point is that these effects are operating within the boundaries of Nifty's DSL (domain specific language). So if you implement custom effects **that you expect Nifty Gui to manage and render**, then they need to be built in a similar way.

Don't misunderstand though; you can have all the custom OpenGL code you want **_outside**_ of Nifty Gui. Heck, you could even implement your own custom OpenGL UI and render it either on top of or underneath the Nifty Gui UI. But keep those two ideas separate because really, you have no idea how Nifty Gui is going to manipulate the OpenGL state machine. It does all sorts of strange kinky things to it in that dark black box of the Nifty rendering system ;-). And threesomes aren't really welcome there. You can have her before or after Nifty, but not during ;-).

It may be that you are trying to accomplish something simple, just going about it in the wrong way. So please, show us teh codez. =)

**Comment by spaceemotion** [comment]
Well, I want to draw 3D object as an effect onto my 2D layers. This might sound a bit crazy, but my items are 3D objects (sometimes 2D as well though). Since I know that my application will only be using OpenGL, I don't really need to rely on an extra abstraction layer for my application only.

The "problem" I am facing here, is that I want to draw 2D things over the previously rendered 3D objects (as overlays) - mainly text labels, but also tooltips and things like that. That's why I tried splitting things up to be on separate layers. Otherwise I could just use the element's position and draw my 3D stuff after nifty rendered its stuff.

**Regarding some example code:**
I cannot really post 1k lines here can I :D?
Here's my custom effect though: http://hastebin.com/cenarucifi.java.
The two custom classes (GuiHelper and WrappedElement) look as follows: 

**GuiHelper:**

``` java
package net.xxxx.client.gui;

import de.lessvoid.nifty.effects.Effect;
import de.lessvoid.nifty.effects.EffectEventId;
import de.lessvoid.nifty.effects.EffectImpl;
import de.lessvoid.nifty.elements.Element;
import de.lessvoid.nifty.elements.render.ElementRenderer;
import de.lessvoid.nifty.screen.Screen;
import net.xxxx.client.gui.elements.WrappedElement;

import java.util.List;

/**
 * Represents the GuiHelper.
 *
 * @author spaceemotion
 * @version 1.0
 */
public final class GuiHelper {
    private GuiHelper() {
        // Intentionally left blank
    }

//...

    public static <T extends ElementRenderer> WrappedElement<T> getWrappedElement(Screen screen, String id, Class<T> renderer) {
        return getWrappedElement(renderer, screen.findElementById(id));
    }

    public static <T extends ElementRenderer> WrappedElement<T> getWrappedElement(Element parent, String id, Class<T> renderer) {
        return getWrappedElement(renderer, parent.findElementById(id));
    }

    private static <T extends ElementRenderer> WrappedElement<T> getWrappedElement(Class<T> renderer, Element element) {
        if (element != null) {
            T elementRenderer = element.getRenderer(renderer);

            if (elementRenderer != null) {
                return new WrappedElement<T>(element, elementRenderer);
            }
        }

        return null;
    }

//...

}
```

**WrappedElement:**

``` java
package net.xxxx.client.gui.elements;

import de.lessvoid.nifty.elements.Element;
import de.lessvoid.nifty.elements.render.ElementRenderer;

import javax.annotation.Nonnull;

/**
 * Represents a wrapped nifty element.
 *
 * @author spaceemotion
 * @version 1.0
 */
public class WrappedElement<R extends ElementRenderer> {
    private final Element element;
    private final R renderer;


    public WrappedElement(@Nonnull Element element, @Nonnull R renderer) {
        this.element = element;
        this.renderer = renderer;
    }

    @Nonnull
    public Element getElement() {
        return element;
    }

    @Nonnull
    public R getRenderer() {
        return renderer;
    }

}
```

The real trouble is, that nifty renders its content after I rendered my 3D content. If I could somehow force all stored batches to be rendered, then proceed it would be all fine (i think).

I hope this helps to clarify my situation ;)

**Comment by relu91** [comment]
I actually can't help you but just to clarify a bit , are you trying to achieve something like Borderlands gui?
![noimage](http://www.shamusyoung.com/twentysidedtale/images/borderlands_loot6.jpg)

Maybe a simple image or a schema could helps...

**Comment by spaceemotion** [comment]
Thanks for all the support, but I finally got it to work with some help by @void256 through the IRC channel ;)

No, I definitely need 3D boxes and stuff, not a pre-translated 2D layer.

I finally got it working using a modified render device and modified batched renderer.
I can now just say `flushBatches()` and all previously saved batches will get drawn to the screen. One small downside is, that this will force a new batch to be drawn (otherwise we'd get a BufferOverFlow).

In case you'd like to know how I did that, here's the code:

First, create a new RenderDevice:

``` java

    public class CustomBatchRenderDevice extends BatchRenderDevice {
        private final CustomBatchRenderBackend backend;

        private Field blendMode;
        private Field atlasTextureId;


        public CustomBatchRenderDevice() {
            this(new CustomBatchRenderBackend(
                    new LwjglGL(),
                    new LwjglBufferFactory(),
                    new LwjglImageFactory(),
                    new LwjglMouseCursorFactory()));
        }

        private CustomBatchRenderDevice(CustomBatchRenderBackend backend) {
            super(backend);

            this.backend = backend;
        }

        @Nonnull
        public CustomBatchRenderBackend getBackend() {
            return backend;
        }

        public boolean prepareFields() {
            try {
                if (blendMode == null) {
                    blendMode = FieldUtils.getField(getClass(), "currentBlendMode", true);
                }

                if (atlasTextureId == null) {
                    atlasTextureId = FieldUtils.getField(getClass(), "currentAtlasTextureId", true);
                }

            } catch (IllegalArgumentException e) {
                client.getLogger().warn("Could not access device field(s)", e);
            }

            return blendMode != null && atlasTextureId != null;
        }

    }
```

then create the custom backend:

``` java

    public class CustomBatchRenderBackend extends BatchRenderBackendInternal {
        private final Collection<Batch> rendered = new LinkedList<Batch>();
        private final GL gl;

        private List<Batch> batches;


        private CustomBatchRenderBackend(@Nonnull GL gl,
                                           @Nonnull BufferFactory bufferFactory,
                                           @Nonnull ImageFactory imageFactory,
                                           @Nonnull MouseCursorFactory mouseCursorFactory) {
            super(gl, bufferFactory, imageFactory, mouseCursorFactory);

            this.gl = gl;
        }

        @SuppressWarnings("unchecked")
        private List<Batch> getBatches() {
            if (batches == null) {
                try {
                    Field[] fs = getClass().getSuperclass().getDeclaredFields();
                    for (Field f : fs) {
                        if (!f.getName().equals("batches")) {
                            continue;
                        }

                        f.setAccessible(true);
                        batches = ((ArrayList<Batch>) f.get(this));
                        break;
                    }

                } catch (IllegalAccessException e) {
                    throw new RuntimeException("Unable to access super batches field!");
                }

                if (batches == null) {
                    throw new RuntimeException("Was unable to get super batches field!");
                }
            }

            return batches;
        }

        @Override
        public void beginFrame() {
            super.beginFrame();

            // Clear previously force-rendered batches
            rendered.clear();
        }

        public void flushBatches() {
            flushBatches(true);
        }

        private void flushBatches(boolean createNewBatch) {
            gl.glEnable(gl.GL_TEXTURE_2D());
            gl.glEnable(gl.GL_BLEND());

            gl.glEnableClientState(gl.GL_VERTEX_ARRAY());
            gl.glEnableClientState(gl.GL_COLOR_ARRAY());
            gl.glEnableClientState(gl.GL_TEXTURE_COORD_ARRAY());

            for (Batch batch : getBatches()) {
                // Skip previously rendered batches
                if (rendered.contains(batch)) {
                    continue;
                }

                batch.render();

                // Also add to rendered batches
                rendered.add(batch);
            }

            gl.glDisableClientState(gl.GL_TEXTURE_COORD_ARRAY());
            gl.glDisableClientState(gl.GL_COLOR_ARRAY());
            gl.glDisableClientState(gl.GL_VERTEX_ARRAY());

            if (createNewBatch && getRenderDevice().prepareFields()) {
                try {
                    beginBatch(((BlendMode) getRenderDevice().blendMode.get(getRenderDevice())),
                            ((Integer) getRenderDevice().atlasTextureId.get(getRenderDevice())));

                } catch (IllegalAccessException e) {
                    // Log this ....
                }
            }
        }

        @Override
        public int render() {
            // Just flush the batches and thus only render batches we didn't render before this time
            flushBatches(false);

            gl.glDisable(gl.GL_TEXTURE_2D());
            gl.glDisable(gl.GL_BLEND());

            return getBatches().size();
        }

    }
```

Now you can use it in your code by calling the `flushBatches()` function ;)

You might notice that I used some reflection in here - I might do a PR to add this feature in the future, but this method work just fine … Maybe @3xp0n3nt could try to add that in a cleaner way ^^

**Comment by ghost** [comment]
Wow, that seems like a pretty nasty hack. Did you even read my last post? You're extending internal classes that are subject to change at any time. It's completely implementation-dependent. Good luck with that next time I update the batch rendering system and completely break your code (accidentally of course).

Just because you **_can**_ do something doesn't mean it's a good idea.

**Comment by relu91** [comment]
Well maybe he just won't to have compatibility with the next versions... It could be that his game won't be updated from gui side and he want only to finish it. Anyway if the user doesn't have the freedom of rendering his own things inside nifty , why don't enchant a little bit the apis of the render engine ? I saw that the NiftyRenderEngine interface it's pretty limited to do simple things , like render a quad, an image and some text , no polygons for example and no Circle. That's good for the propose of rendering a simple gui but the effects could need some more powerfull api don't you think?. Could it be possibile? or the difference between the renderbackends are too much?. This is not a blame to the nifty renderer system , I just say here because is on topic :) .

**Comment by spaceemotion** [comment]
Well, like I said in my post, I talked to @void256 already and he suggested that I should do a PR about that so it can be implemented officially. That way my code wouldn't break in future updates as well.

I did read your post, @3xp0n3nt, but my problem is, that I want to render my custom stuff within two nifty layers (or batches) - like you said with "sandwiching custom OpenGL rendering between two Nifty layer elements".
My game renders its normal screen, then nifty starts the 2D overlays (backgrounds, ....), then I wanted to have my custom effect and then some nifty overlays again (for tooltips, popups, …). If I would do that completely separately from Nifty I would either have to have 2 nifty instances (not very great) or no overlays (not an option).

Forcing the batches to draw sounded like a pretty good solution to me, and it is working dandy-fine ;)
This method now also allows me to do stencil-buffer or alpha-test based progress-bars (e.g. for circular bars, more about this technique can be read [here](http://www.gamedev.net/topic/603658-circular-health-bars/)), since I can set that value upfront and call the flush method.

I don't really like those "hacks" using reflection either, but as @relu91 said correctly, I just wanted to quickly get some results done - I can always change this part later on ;).
I also agree that Nifty should have some more support for custom element types and / or renderers ;)

**Comment by void256** [comment]
This solution is really a bit .. hardcore :wink:  but yes, I still think, we'll need something like that in regular Nifty. Although it should be very clear what flushing the batches manually means - you shouldn't really do it all over the place for instance :wink: but for the use case of @spaceemotion it's a valid approach I guess.

A pull request would be appreciated for this!

Well, thinking about this a bit more ... maybe it would be better to have that control for flushing the batches explicit in a layer. So for instance: what if you could add a `flushBatches="true"` or something to a Nifty layer?

So that everything that is rendered in that layer could then be custom rendered by an effect?

Ok, maybe I don't like that :smile: because batches are really an implementation detail ... but I do see the need to have some support for this for special cases though

**Comment by spaceemotion** [comment]
That XML-thing would indeed be a nice idea. I wouldn't really call it "flushBatches" though, maybe something more general - something that describes that the output will be force-rendered ("forceRender", "flushRenderer", "forceRendering", …).

> So that everything that is rendered in that layer could then be custom rendered by an effect?

What exactly do you mean by that? From what I understand you'd make it up to the developer to render the elements? If that's what you meant, this would also be a cool idea, although it might get very complex for the developer itself very quickly. A simple, "hey I can add my stuff between nifty layers" would be sufficient ;)

**Comment by void256** [comment]
I was just thinking about the current way to do custom rendering which would be inside of a NiftyEffect attached to some element on that special layer.

BUT

you are right ... if there would be some kind of custom rendering callback ... that might be even more direct! :grinning: like a special layer with some custom onRender callback method or something. In this callback you basically can render anything you want - just make sure that you don't modify any states that Nifty has set up. And then, if you'd have another layer on top of that special one, Nifty would just continue rendering regulary.

**Comment by spaceemotion** [comment]
That could work as well … ~~and would remove the need of some extra tag as well ;)~~ okay, maybe not, if it's something like a screen controller, just for layers...

**Comment by ghost** [comment]
> just make sure that you don't modify any states that Nifty has set up. And then, if you'd have another layer on top of that special one, Nifty would just continue rendering regulary.

@void256 Nifty should automatically save and restore the OpenGL state because you really have no idea how a user is going to ~~destroy~~ modify it.

While I completely disagree with the way @spaceemotion implemented a solution, I do agree that this could become a built-in feature if done properly.

**Comment by void256** [comment]
@3xp0n3nt yes, I completely agree! Actually that's something we should add independently from the current issue. Some people including @spaceemotion :wink: had problems with figuring out what states to save/reset when combining Nifty with their own rendering. Nifty should make integrating itself into other render engines more easy.

To solve it we should save/restore all the states _we_ need in Niftys render() method. And that being said, I think I'll give up the idea that the user of Nifty has to set up 2d Ortho rendering himself prior to calling Nifty.render() :wink:
