### ISSUE TITLE
Nifty with Lwjgl no text rendering

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#268]
I am using Nifty 1.4 with the Lwjgl to create a menu for a game. However, I can't get nifty to render any text. Panels and other elements are displayed, but text is invisible/not rendered. I am wondering if this is a mistake of mine or if it is a real bug in the library. Any thoughts/advices are welcome.

Here is a link to my question on gamedev.stackexchange containing my .xml and .java as well as a screenshot: http://gamedev.stackexchange.com/questions/81835/niftygui-text-isnt-rendering

**Comment by void256** [comment]
I've answered at gamedev. For reference here is the answer:

You're not setting the projection matrix correctly. At the time you call glOrtho() you probably want to have the GL_PROJECTION matrix mode enabled.

Something like that

```
// set projection matrix
GL11.glMatrixMode(GL11.GL_PROJECTION);
GL11.glLoadIdentity();
GL11.glOrtho(0, 1920, 1080, 0, 1, -1);

// set modelview matrix to identity
GL11.glMatrixMode(GL11.GL_MODELVIEW);
GL11.glLoadIdentity();
```

Also note that Nifty assumes the coordinates (0,0) at the top left corner. That's why the third and fourth parameter should be switched.

**Comment by ghost** [comment]
Thank you for your help, but this doesn't fix the problem. Text still isn't appearing, but everything else looks like before.

**Comment by ghost** [comment]
Thank you for your answer on gamedev! As I thought, it was clearly my fault ^^
