### ISSUE TITLE
NiftyEvent does not need to be generic

### ISSUE THREAD

**Issue by toolforger** [nifty-gui/nifty-gui#29]
Things that point in that direction:
- NiftyEvent itself does not use T
- 90% of subclasses fill in a dummy type or have @SuppressWarnings("rawtypes")
- The few classes that actually use their parameter can just introduce a T

E.g. DropDownSelectionChangedEvent<T> could be generic even if NiftyEvent is non-generic.

Making NiftyEvent non-generic would solve these problems.

Downside: You can't do "implements NiftyEvent<T>" anymore, this needs to be replaced with "implements NiftyEvent".
This is not a problem inside Nifty itself, and the change is trivial anyway.
It would require adaptation in any client code that creates subclasses of NiftyEvent. The changes would still be trivial but would need to be done.
I'm not sure whether that's acceptable or not. It's certainly an incompatible change, i.e. it should not be applied to 1.3.

**Comment by toolforger** [comment]
Oh. Right. The alternative would be to add more @SuppressWarnings("rawtypes") to silence the compiler.

**Comment by void256** [comment]
I think you're right!

Looking at this now NiftyEvent indeed doesn't need to be generic. I think the reason why it became generic is the ListBoxSelectionChangedEvent<T> which, if I remember correclty, was the first of his kind and kinda evolved into the more general NiftyEvent concept and all the other event types.

But I agree with you that generics can be introduced in classes that implement NiftyEvent. The necessary code changes to client code are acceptable when we change this in the master branch and not in 1.3 as you've suggested (and should in general be small since I doubt that there is a whole lot of code out there that uses the NiftyEvent interface - besides Nifty itself).

Can you provide another pull request for this? Alternatively I can perform that change in the master branch on my own.

What do you think?

**Comment by toolforger** [comment]
Preparing pull request...
(always been doing pull requests for master... at least I hope so)

**Comment by void256** [comment]
https://github.com/void256/nifty-gui/pull/30
