### ISSUE TITLE
Manual setting for localization bundle encoding

### ISSUE THREAD

**Issue by smirnovegorv** [nifty-gui/nifty-gui#303]
In 1.4.0 the signature of method used for adding localization bundles has changed. It now accepts only bundle file name, and there is no way to affect how it is loaded.

By default, java properties are loaded in ISO 8859-1 encoding. However, it is quite restricted and, for example, does not contain cyrillic letters, that are needed for localizing game in russian and some other ex-USSR languages.

In 1.3.2 I could use the UTF-8 property files by loading them myself and manually setting the right encoding. In 1.4.0 it is no longer possible, so it is now quite difficult to localize GUI to a language that uses non-latin alphabet (you should make your text in UTF-8, then use some converter to make them 8859-encoded with utf escaping and use them in game, one extra step in a build process)

There should be some method that accepts pre-loaded ResourceBundle, like it was before, or it should accept the Reader class instead of a file name, just like ResourceBundle does

**Comment by bgroenks96** [comment]
Which method signature and in what class are you referring to?

I am seeing no changes to Nifty.addResourceBundle between 1.3 and 1.4.

**Comment by smirnovegorv** [comment]
In 1.3 Nifty class had a `Map<String, ResourceBundle> resourceBundles`field.
In 1.4, it has a `Map<String, String> resourceBundles`, and actual ResourceBundle objects are loaded internally somewhere.

**Comment by bgroenks96** [comment]
This appears to be a side effect of commit 9547ad16a838a992927333303157c78a988f81b0 which addresses issue #100 (still open).

@void256 I will need your input on this for why exactly the `resourceBundles` HashMap had to be changed to `<String,String>` as opposed to `<String,ResourceBundle>`.

It seems to me like it might be possible to go back to the previous HashMap type and simply retain the implementation of `getResourceBundles` to return a String version... with the addition of another method possibly to allow direct access to `ResourceBundle`

**Comment by void256** [comment]
We need to get the ResourceBundle at the moment someone calls nifty.setLocale() so that we can dynamically change the locale. This is done in the SpecialValuesReplace class where we now use the stored String from that HashMap to resolve the ResourceBundle with the current locale.

If we would store the ResourceBundle - which is already locale specific - then we'd loose this ability to request a different ResourceBundle for a different locale later.

I think this was the reason I've kinda used this brute-force approach.

Looking back at it now I think it would have been better to still allow the ResourceBundle to be stored. However, in that case we should store them locale specific and the user has to be able to provide different ResourceBundles for all the locales he wants to support.

**Comment by bgroenks96** [comment]
Would you have time to make this change then? You wrote it, so you're less likely to mess something up than I am :wink:

**Comment by void256** [comment]
There you go: 7455f39f7c896ab942ff8ff19e3d5bdae3feca29

I've not tested the new addResourceBundle() method. Can you do that please @jedi-philosopher ? I've only tried the old way using the LocalizeExample which appears to still work.

Always remember that making a donation for Nifty GUI is appreciated! :smile:

**Comment by smirnovegorv** [comment]
Checked it, utf-8 bundles now load fine, just like before. Didn't check runtime locale change, however, as it is not used in my game. Thanks.
