### ISSUE TITLE
getRenderDevice() method in NiftyRenderEngineImpl returns wrong object

### ISSUE THREAD

**Issue by barefists** [nifty-gui/nifty-gui#318]
getRenderDevice() in NiftyRenderEngineImpl returns an instance of ScalingRenderDevice rather than the RenderDevice I assigned to Nifty during construction.

**Comment by void256** [comment]
Yes, this is to support the nifty.enableAutoScaling() feature where you can design your GUI with a specific base resolution and then provide a scale factor to scale it up or down to match your actual resolution.

Internally the actual RenderDevice implementation is wrapped into the ScalingRenderDevice to provide this functionality but all calls will be forwared to the actual RenderDevice implementation (eventually with modified parameters). Currently you can't directly access your specific RenderDevice this way.

In general I would argue that one shouldn't depend on a specific implementation anyway. In your case it's probably because of the Processing integration you're doing. Is there maybe another way to solve that? What exactly do you need the specific RenderDevice implementation for?

You can find more details about the ScalingRenderDevice in the commit that initially introduced this feature here fdb2f55d0b3f810d8e2cfbe4125874f685ebea4e

**Comment by barefists** [comment]
I'm writing a helper class to handle the updating and drawing of the Nifty canvas onto the screen, without which it can get quite verbose in Processing. To do so I need the PApplet processing is running in, the Nifty instance and the canvas that Nifty is drawing on.

Right I'm experimenting with an extension of the main Nifty class to do the abovementioned. Issue with this is that I can't write anything before the superclass constructor, and trying to get the RenderDeviceProcessing reference after constructing Nifty is proving difficult.

Alternatively, I could write a wrapper class around Nifty, but interacting with Nifty from processing would require a getNifty() call or something, and would be sightly more complex.

EDIT: I realize JME3 does something similar to what I described in the alternative. Doesn't look as bad as I thought actually.

**Comment by bgroenks96** [comment]
Why doesn't ScalingRenderDevice just provide a public accessor method to grab the internal RenderDevice reference? It probably should... since it does seem kind of unfair that Nifty would just sneakily wrap the specific implementation and return the wrapper instead of the provided RenderDevice. Definitely not what would be intuitively expected.

**Comment by void256** [comment]
@bgroenks96 I don't agree. According to the API all you get is the RenderDevice interface. Depending your code on the actual implementation is not a good idea at all. Since this code will always break if you later decide to use a different RenderDevice implementation. We shouldn't encourage anyone to go this route since it will lead to the dark side :wink:

@barefists I don't quite get it :smile: Can you provide an example sketch or something so that I understand the problem a bit more?

**Comment by barefists** [comment]
@bgroenks96 Haha yeah, that was what I thought originally. Seems intuitive that getRenderDevice() should return the original RenderDevice I passed it during construction.

@void256 I've since gone with the alternative method I mentioned earlier, which is similar in structure to the NiftyJmeDisplay class. For the sake of clarity, this was what I was trying to do earlier:

``` java
/**
 * Nifty wrapper and helper class for Processing.
 * @author Xuanming
 */
public class NiftyProcessing extends Nifty {

    private final PGraphics graphics;
    private final PApplet app;

    /**
     * Instantiate the Nifty wrapper for Processing.
     * @param app PApplet instance Processing is running in.
     * @param soundDevice Implementation of Nifty's SoundDevice interface.
     * @param timeProvider Implementation of Nifty's TimeProvider interface.
     */
    public NiftyProcessing(final PApplet app, final SoundDevice soundDevice, final TimeProvider timeProvider) {
        super (new RenderDeviceProcessing(app), soundDevice, new InputSystemProcessing(app), timeProvider);

        // Grab PApplet and register draw() method.
        this.app = app;
        app.registerMethod("draw", this);

        // Grab PGraphics canvas from RenderDevice.
        this.graphics = ((RenderDeviceProcessing)this.getRenderEngine().getRenderDevice()).getCanvas();
    }

    /**
     * Method attached to Processing's native draw() method using registerMethod().
     * This gets called every frame before drawing ends in Processing.
     */
    public void draw() {

        // Update canvas.
        graphics.clear();
        graphics.beginDraw();
        update();
        render(false);
        graphics.endDraw();

        // Draw canvas onto screen.
        app.image(graphics, 0, 0);
    }
}
```

I've since changed it to the following:

``` java
/**
 * Nifty wrapper and helper class for Processing.
 * @author Xuanming
 */
public class NiftyProcessing {

    private final PGraphics graphics;
    private final PApplet app;
    private final Nifty nifty;

    /**
     * Instantiate the Nifty wrapper for Processing.
     * @param app PApplet instance Processing is running in.
     * @param soundDevice Implementation of Nifty's SoundDevice interface.
     * @param timeProvider Implementation of Nifty's TimeProvider interface.
     */
    public NiftyProcessing(final PApplet app, final SoundDevice soundDevice, final TimeProvider timeProvider) {     

        // Grab PApplet and register draw() method.
        this.app = app;
        app.registerMethod("draw", this);

        // Create RenderDeviceProcessing and grab the PGraphics object from it.
        RenderDeviceProcessing renderDevice = new RenderDeviceProcessing(app);
        this.graphics = renderDevice.getCanvas();

        // Initate Nifty.
        this.nifty = new Nifty(renderDevice, soundDevice, new InputSystemProcessing(app), timeProvider);
    }

    /**
     * Grab the instance of Nifty contained in this class.
     * @return The Nifty instance.
     */
    public Nifty getNifty() {
        return nifty;
    }

    /**
     * Method attached to Processing's native draw() method using registerMethod().
     * This gets called every frame before drawing ends in Processing.
     */
    public void draw() {

        // Update canvas.
        graphics.clear();
        graphics.beginDraw();
        nifty.update();
        nifty.render(false);
        graphics.endDraw();

        // Draw canvas onto screen.
        app.image(graphics, 0, 0);
    }
}
```
