### ISSUE TITLE
setVisible seems recursive

### ISSUE THREAD

**Issue by harlock76** [nifty-gui/nifty-gui#331]
hello,

I use setVisible on a hidden panel, and all its hidden children appear although they are defined as visible="false" and should appear later in the code, not when the parent shows up

```
    <layer id="nodesInfosLayer" backgroundColor="#0000" childLayout="absolute">
        <panel id="nodesInfosPanel" width="100" height="100" backgroundColor="#0000" childLayout="absolute" visible="false"> 
            <panel id="hudGlassPanel" x="35" y="-43" width="160" height="133" backgroundColor="#0000" childLayout="absolute" visible="false"> 
                <image id="hudGlassImage" x="0" y="0" width="160" height="133" filename="Textures/hud_glass.png" />
            </panel> 
        </panel>
</layer>
```

is there a way to preserve children states when parent.setVisible(true) is called ?
so far, I set the parent visible and manual set invisiible the children, wich is tedious and prone to errors
also it does not make sens to have children visible while parent is not

thanks

**Comment by void256** [comment]
Which Nifty version do you use?
The whole recursive setVisible thing should be fixed in 1.4.x, see this commit for details https://github.com/void256/nifty-gui/commit/c8a6030e78225cb5dc7a4cc3aba22df686339b68 and issue #43 as well.
I've not tried your example but from what I understand this should work as expected in 1.4.x. There have been some more changes lately so can you try it in the latest Nifty too, which is 1.4.1?

**Comment by harlock76** [comment]
ok , actualy I use JMonkey 3, maybe they are nt up to date with latest nifty version

**Comment by void256** [comment]
The latest nightly build of jME should actually contain Nifty 1.4.1. Can you check the Nifty version?

There is a method on the Nifty instance that returns the version String: https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/Nifty.java#L239
