### ISSUE TITLE
#background id raising possible conflicting id warning

### ISSUE THREAD

**Issue by harlock76** [nifty-gui/nifty-gui#333]
hello,

I get this error
WARNING: Possible conflicting id [#background] detected. Consider making all Ids unique or use #id in control-definitions.

while I use a # in my control definition

```
     image id="#background" x="0" y="0" width="84px" height="84px" 
```

while it works for other controls

is background id a special case ?

thanks

**Comment by harlock76** [comment]
??

**Comment by bgroenks96** [comment]
Are you using #id with other controls?

**Comment by harlock76** [comment]
well actually I always assumed it was id="#identifier" witch works well when having duplicate id warning
so I'll try #id="identifier"

**Comment by bgroenks96** [comment]
That's not what I meant. #id="" won't work.

I meant are you using `id="#identifier"` with other controls?

**Comment by harlock76** [comment]
yes, funny thing is that with other controls I dont have this issue
I also tried id=#back-ground" still the same issue

```
<!-- BUTTON COMPONENT - - - - - - - - - - - - - - - - - - - - - - - - - - -->  
<controlDefinition name="buttonComponent" controller="mygame.gui.CommandButtonController" >
  <interact onPrimaryClickRepeat="pushButton()" onPrimaryRelease="$action" />   
  <panel width="84" height="84" childLayout="absolute" >
     <effect>
        <onStartHover name="commandButtonEffect" state="on" neverStopRendering="false" />
        <onEndHover   name="commandButtonEffect" state="off" neverStopRendering="false" />
     </effect>
     <image id="#background" x="0" y="0" width="84px" height="84px" filename="Textures/button.png"/>
     <image x="10" y="10" width="64px" height="64px" filename="$icon"/>
     <control name="label" x="2" y="70" width="80" height="10" text="$caption"  wrap="false" color="#ffff" textHAlign="center"/>
  </panel>
</controlDefinition>
```

**Comment by bgroenks96** [comment]
I'm not sure. We'll have to wait for input from @void256 on this.

**Comment by void256** [comment]
Iirc Nifty will use the #someid syntax of child elements together with the parent id to build a unique id. So if you use your button component it's probably a good idea to give that button an id as well, so that the resulting id would be "yourbuttonid#background".

I think if you omit the id from the button control and you have multiple buttons on your screen then you might end up with two ids having the same id "#background" which will lead to that message.

But I'm not sure and I haven't check it - I might be wrong :wink:

But to verify you could do a `screen.debugOutput()` and post the resulting OUTput somewhere or better yet, take a look yourself. Again iirc that debug output should display all id's so if there is some duplication you should be able to see it.

**Comment by harlock76** [comment]
well it complains about duplicates, but I use #background as id, hence the reason I posted this question
I'll check the debug output...

**Comment by harlock76** [comment]
ok I got rid of id by givind an id to the pareent control, 
thanks
