### ISSUE TITLE
Listen for events on particular element or control, outside ScreenController?

### ISSUE THREAD

**Issue by arakash92** [nifty-gui/nifty-gui#347]
As the title says, is it possible?

Something like this:

``` java
Button button = screen.findNiftyControl("myButton", Button.class);
button.addEventListener(new SomeInterface() {
    public void click() {
        System.out.println("Clicked myButton!");
    }
});
```

**Comment by relu91** [comment]
No, it's not possible. All event handling is done in a Controller ( as far I can tell ). In this issue #290 I was addressing something similar but now I don't have time to work in nifty, unfortunately :cry: .

**Comment by void256** [comment]
If you would be willing to use the EventBus then it would be possible. The [Nifty manual](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/manual/nifty-gui-the-manual-1.3.2.pdf) describes this on Page 81 how to listen for EventBus events on any instance:

```
You'll need to call nifty.subscribeAnnotations() with an instance of your class.
Nifty will then scan the given instance for all @NiftyEventSubscriber annotations
and subscribe all of them with the EventBus.

If you don't need your object anymore you should call nifty.unsubscribeAnnotations()
with the instance again to unsubscribe all annotated methods.
```

With the basic event handling, the interact methods, I think relu91 is right. Theoretically you could try to attach a ElementController to the element in question though. This way all interact methods will be first looked up on the ElementController and second on the ScreenController. This is explained in the manual as well. I think this will work for basic elements.

However the controls, like the Button control in your example already use this feature to add their own event handling to themself already. I'm not sure what happens when you add your own EventController on top of that :smile: Might work but I'm not sure. In retrospect a lot of Nifty is awkward :wink:

I'd suggest going the event way tho.

**Comment by bgroenks96** [comment]
Looks like @void256 and @relu91 have sufficiently answered this question. Reopen if there are any further issues.
