### ISSUE TITLE
Maven hosting service 503 Error

### ISSUE THREAD

**Issue by SonarBeserk** [nifty-gui/nifty-gui#387]
The website for maven packages http://nifty-gui.sourceforge.net/ is having a 503 error. This is currently preventing smooth builds.

**Comment by bgroenks96** [comment]
Thanks for reporting this.

It's giving me a 404 error now, actually. @void256 Please take a look ASAP.

**Comment by bgroenks96** [comment]
@void256 Check out the last build (from November) for Nifty 2.0 on Illarion's CI server. It was triggered by a CoreGL update, but it appears to have failed due to some failure in retrieving Nifty artifacts:
https://illarion.org:8080/job/Nifty-2.0.x-SNAPSHOT/102/

**Comment by SonarBeserk** [comment]
When I contacted him on twitter he said that it is likely an issue of Sourceforge having poor uptime. However Im not sure why there would be a 404.

**Comment by mkaring** [comment]
The sourceforge servers are often acting up. Timing out, sending strange errors and stuff. Maybe we can convince @void256 to move to another hosting server. Sonatype or maven central... at least for the stable builds.

**Comment by void256** [comment]
The correct URL is: http://nifty-gui.sourceforge.net/nifty-maven-repo/ and it seems to work for me now again. I did get 503 Errors last night but as far as I see they are gone.

Also: https://issues.sonatype.org/browse/OSSRH-19476 :smile: Not sure if it goes through tho. Eventually they don't like our groupId "lessvoid" and we'll probably need at least the "jglfont" to be available in the central too which might require some more work (mainly adding code signing to the project). But we'll see what Sonatype says.

**Comment by spaceemotion** [comment]
Good luck! They usually respond within a few hours (max a day) :)

**Comment by void256** [comment]
Alright, our first try was rejected because of:

```
lessvoid is an invalid groupId.  Please read:
http://central.sonatype.org/pages/choosing-your-coordinates.html

You may also choose a groupId that reflects your project hosting
in this case, something like com.github.void256
```

I kinda expected that since "lessvoid" is missing some top-level domain like "com" :wink:

It doesn't need to contain "lessvoid" but I think `com.lessvoid` would be accepted since I do own that domain. But we could go with `com.github.void256` as well - as they've suggested. However, I don't like that because Nifty doesn't need to be connected with my username. I'd like it to be more general and public. **Any suggestions what groupId Nifty should use?**

PS: This also means that we won't get old releases into the central repo "as-is" since a change of "groupId" is necessary. So if we still want Nifty in the central it would require the use of the new groupId.

**Comment by spaceemotion** [comment]
Ah, right they do check the domains.

Maybe it's not a bad idea to make nifty more "global" by changing the groupId to something like `net.niftygui` or `com.niftygui` (you would have to own the domain first, though) – obviously `nifty.com` and `nifty.net` are already taken.

**Comment by bgroenks96** [comment]
Wait... is there a reason de.lessvoid won't work? That seems like the most obvious choice.

**Comment by void256** [comment]
`de.lessvoid` won't work right now because I don't own the domain and Nifty is not really a `de` project anymore :smiley: I already think of it as being more international.

`com.lessvoid` would be possible already but I'm not sure it should stay under `lessvoid` at all.

@spaceemotion Leaving out the "gui" part leads to some strange domains :wink:

However `net.niftygui` or `org.niftygui` or even `com.niftygui` are still available and sound good to me. I would prefer `org` though and I think I can afford owning another domain.

Any more opinions or comments?

**Comment by mkaring** [comment]
A possibility would also be to create a dedicated github organization for the nifty-gui and use that as domain reference.

**Comment by void256** [comment]
excellent idea! I've just set up https://github.com/nifty-gui :smile:

**Comment by void256** [comment]
Since I like the "nifty-gui" organization idea I sent out member invites for existing collaborators. You should get an email invite by github so that you'll keep write access to the new repo.

If I understood everything correctly I can transfer the original `void256/nifty-gui` repo to `nifty-gui/nifty-gui` with a single button press keeping all the git history and the issues intact.

Any objections or should I go ahead? :sweat_smile:

**Comment by mkaring** [comment]
Don't let anyone stop you. Just do not forget to update the build server after you are done. I do not like if it fires errors. ;)

**Comment by void256** [comment]
Done! I've already updated the 1.4 branch with the new groupId and the Sonatype issue as well. 

**Edit:** Sonatype responded quickly and we're now able to deploy SNAPSHOT builds as well as stage release builds for central.

Welcome your new home:

``` XML
<groupId>com.github.nifty-gui</groupId>
<artifactId>nifty</artifactId>
<version>1.4.2-SNAPSHOT</version>
```

But you'll still need to add both repositories to your pom.xml for now:

``` XML
  <repositories>
    <!-- only needed for snapshot builds starting with 1.4.2-SNAPSHOT -->
    <repository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </repository>
   <!-- still needed for some other dependencies not yet available in central like jglfont -->
    <repository>
      <id>nifty-maven-repo.sourceforge.net</id>
      <url>http://nifty-gui.sourceforge.net/nifty-maven-repo</url>
    </repository>
  </repositories>
```

The "ossrh" is only required if you plan to use Nifty SNAPSHOT builds. After 1.4.2 is released and everything works out ok then this will NOT BE REQUIRED anymore.

For now the `nifty-maven-repo.sourceforge.net` repository is still needed because there are a couple of libs only deployed there, like "jglfont". We need to move these to the central next @bgroenks96 :wink:

**Comment by void256** [comment]
Since http://nifty-gui.sourceforge.net/ should be available again and new builds will be deployed to sonatype anyway, I'll close this issue now.
