### ISSUE TITLE
NiftyColor

### ISSUE THREAD

**Issue by mkaring** [nifty-gui/nifty-gui#391]
The NiftyColor class needs some reconsideration in the current implementation for Nifty 2.0

The functions for fetching the "standard" colors do not contain any caching of instances but instead perform a expensive parsing from a string constance every time the function is called.

What was the idea behind implementing those constant colors as functions and not as static constants? The `NiftyColor` class is immutable and would work very well when used as constants?

For our examples this class is currently mostly responsible for the generated memory garbage.

**Comment by void256** [comment]
I agree! This should be changed. The static methods should return color constants instead of parsing the color strings on each call. That sounds indeed really stupid in retrospective. Preventing memory garbage is essential for Nifty!

I don't see any real reason that these are static methods instead of constants. However, having them as methods will eventually provide a better API evolution compared to allowing direct access to a static constant. That's the only idea that might have motivated it.

**Comment by relu91** [comment]
> I don't see any real reason that these are static methods instead of constants. However, having them as methods will eventually provide a better API evolution compared to allowing direct access to a static constant. That's the only idea that might have motivated it.

So what should we choose? public static methods with private static variables or only public static variables ? 
I can handle this! ^^

**Comment by relu91** [comment]
There's some reason to leave static methods there? maybe they are called somewhere using reflection?

**Comment by void256** [comment]
I would suggest to just keep the public static methods and return a private constant.

**Comment by relu91** [comment]
Why? I know that NiftyColor is widely used in nifty and a change to the api means a lot of changes somewhere else, but I don't think it's worth to keep static methods, it only introduces overhead...

**Comment by void256** [comment]
Because I like the colors to be written in lower case letters and if they are constants we would probably write them in upper case? :wink:
I don't think it's going to be a catastrophic runtime cost to have these as methods instead of constants. And if we ever want to track something silly like how many times a specific color is being used .. then we only can do that with methods and not when we reference the constants directly :smile:

**Comment by bgroenks96** [comment]
I agree with @void256 about returning the private constant. The constants can be initialized at load time in the same manner the public methods are doing it now, and then the public methods can just return those values. Hooray for efficiency!

There are other less silly reasons to do it this way as well. For example, we may at some point want to allow manipulation of NiftyColor so that one or more of the color channels is always biased by some pre-configured factor (i.e. maybe having all colors offset by a gamma constant).

**Comment by void256** [comment]
Yes @bgroenks96 and it would still be runtime compatible to previous versions of that class too. I mean you could drop in the new class and don't even have to recompile all of the dependent classes. Not that any of that really matters in this case tho :wink:

And for runtime overhead that's really difficult to discuss without being a JVM specialist but I would strongly assume the compiler or the runtime to be so smart about this to optimize the method call away anyway. And if it does not and these calls ever show up in some cpu profiler we can still optimize it away ourself but I doubt that's going to be the case.

I still like the idea to have the possibility to later introduce additional code in these methods and would always prefer it over plain constants to be honest.

**Comment by bgroenks96** [comment]
The JVM overhead between a static constant and a static method returning a static constant is most definitely negligible.

**Comment by relu91** [comment]
Ok, you have convince me! :smile: , I'll do it ASAP !

**Comment by bgroenks96** [comment]
:+1:

**Comment by mkaring** [comment]
I am not sure I like the way this issue was resolved. :(

The problem is that now we got two placed where the named colours are mapped to a colour value. Once in the constants and once the the `ColorStringParser` that contains the mapping table. While it is unlikely that those colour values ever change, it is still not ideal to have these mappings in the code twice.

From my point of view there are two solutions to this. Either the constants are created using the `ColorStringParser` or the `ColorStringParser` fetches the `NiftyColor` instances for the named colours from the defined constants. Since both classes have dependencies in both directions anyway, it does not really matter what solution is used. My gut feeling tells me it would be better design to keep the definitions in the `ColorStringParser`. But that is just me.

What do you think?

**Comment by relu91** [comment]
Yeah sorry I forgot about that! Sending an other pull request soon! I would prefer instead that color parser uses the constants in NiftyColor.

**Comment by relu91** [comment]
Commit 7fc06bc fixes the issue
