### ISSUE TITLE
remove recursive call in Element.setVisible() method (#27 on sourceforge)

### ISSUE THREAD

**Issue by void256** [nifty-gui/nifty-gui#43]
Moved from sf.net bugtracker to github issues. Base is -> http://sourceforge.net/p/nifty-gui/bugs/27/

---

https://sourceforge.net/projects/nifty-gui/forums/forum/807892/topic/4478259

Recursive call in setVisible()/setFocusable() may incur unexpected results to element hierarchy.
Let's say, element A has B1, B2, B3, B4, C as children.
user want to show B1, B2, B3, B4 but not C.
C is shown only for a specific situation.
In such situation, user have to call setVisible(true) for each B*.
It's not only inconvenient but also weird.

I think setting some value to parent element should not change child element properties.

I changed the setVisible()/isVisble() code and confirms it works well on AllExamplesMain.
But setFocusable() doesn't work. I don't know why.
So I attach the setVisible() fix only.

---

why do you think that this is a bug?

if you hide element x then all child elements of element x (as well as all child elements of all child elements and so on) will be hidden too. this is intended behaviour.

and this is not a trivial issue to solve for all cases. your patch breaks some unit tests too.

it "might" be possible to change this but this will be more involving. first of all nifty does currently not check the visibility related to the parent elements (your patch does this but not for all checks - just check how many code lines access the plain visible flag at the element level without checking the parents visibility state).

being very close to 1.3 and being not convinced that this is a bug I don't think I'd like to change this - al least not now.

---

I agree it is not appropriate to fix this because it is about to release 1.3.
It is not important when this patch is applied. But I think it should be applied even later.
This feature will make it very difficult to handle nifty ui.
When someone has a complex UI hierarchy and the visibility is changed often,
it makes the nifty ui management catastropic.
I experienced this situation from my current project so I'm convinced. :(

**Comment by Shirkit** [comment]
I think each element should store it's flag if it's visible or not, and never override children's flag. In the rendering process, not visible elements won't have it's children visited, that way you don't need to override children's flag when it's own flag has changed.

**Comment by toolforger** [comment]
Shirkit's proposal mirrors what Swing and Windows GDI do.
It's generally the reasonable thing to do. Not only is revisiting all subelements awkward, it also means that any code showing a panel must know which subelements should now be visible - however, that knowledge might be far away in different classes.
One example for a use case: Imagine that red stars are shown near input fields that contain invalid input. Further imagine that the entire subpanel holding these fields can be shown or hidden depending on some other option. Now if there is some invalid input, the panel is hidden and shown again, the code that shows the panel needs to know that (a) the input fields exist and (b) which of them need to have their red star shown or not.
Another use case: Don't show the dropdown element of a dropdown control just because the dropdown control became visible.

**Comment by Shirkit** [comment]
It just doesn't makes sense overriding the child's visibility when the
patent changes. I had to rearrange all my UI because of that, 'faking'
children components to make my life easier! I have a fairly complex
situation where groups of buttons gets hidden on shown every five seconds,
at the exact same place, because they are replaced with labels sometimes.

Applying an analogy in real life, say you got kids. And dry your children
got kids, and then your son decides to hide his kid. If you hide yourself,
and then show up again, why your grandson would be shown if his parents
doesn't want to?

Pedro Torres (by cellphone)

**Comment by void256** [comment]
I agree with both of you!

Iirc the problem is that the visibility flag of an Element is not only used while rendering but is checked in other cases as well - f.i. in processing input events. The original patch did not take this into account correctly and "might" have introduced other problems, therefore the delay for Nifty 1.4.

In retrospect the way this currently works in Nifty is kinda odd and should be changed exactly as both of you have proposed. We just need to make sure that other parts don't explode in the process :)

I've not looked into this yet but I can do that again as soon as possible.

**Comment by void256** [comment]
Someone available to test this especially with existing productive code that uses the visibility like that?

The existing unit tests have been modified accordingly: https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/test/java/de/lessvoid/nifty/elements/ElementShowHideTest.java

And I've added a new integration test/example for manual testing here: https://github.com/void256/nifty-gui/tree/1.4/nifty-examples/src/main/java/de/lessvoid/nifty/issues/issue43

**Comment by relu91** [comment]
Tested on my editor seems fine! :+1:

**Comment by void256** [comment]
I haven't noticed any explosions too :wink: I'll close this issue for now!
