### ISSUE TITLE
Screen's rootElement doesn have its screen member set

### ISSUE THREAD

**Issue by toolforger** [nifty-gui/nifty-gui#51]
so myScreen.getRootElement().getScreen() will always return null. This means I can't write code that has just an Element as a parameter.
Can't fix this easily by myself because I wouldn't know where to look for code that might be affected by a fix. (Are there unit tests for all code that might be affected by a change here? If yes, I _can_ try my hand at this... it's just that my impressions is that Nifty wasn't build with robustness in this direction in mind.)

Anyway, I'll have to re-architect my entire screenbuilding approach now - I was assuming I can start the screen running and add stuff without having to thread a Screen parameter to everything.
Some of my code needs getters to decide what to do when creating a subelement, and the Builder classes don't have getters. Would it be a worthy addition to add getters to the Builders? (Not that I'm very happy to have to do that, mind you... but it will give me something useful to do while I'm held up on the rootElement screen issue.)

**Comment by void256** [comment]
I don't see a `element.getScreen()` method here o_O Where are you?

> it's just that my impressions is that Nifty wasn't build with robustness in this direction in mind

Yeah, I know. Nifty should have many more tests. That's true.

But it was not a conscious decision to leave tests out and jeopardize robustness this way ;-) The problem is, it's just too easy to skip writing tests while adding new features and fixing bugs. I think most projects of a reasonable size suffer from this. And some developers don't even know what TDD is or simply refuse to use it.

Oh well. Another thing to make better in 2.0 =P

**Comment by toolforger** [comment]
Ah, that's what I'm working on: I have a new `ElementBuilder.build(Element.Parent)` that does `build(parent.getNifty(), parent.getScreen(), parent)`.
Except `parent.getScreen()` returns `null` if the parent is a `rootElement`.

I think the root cause is that `Screen#bindControls()` isn't setting `rootElement`.
What's the best approach to solve this? I'm considering replacing the body with `bound = true; rootElement.bindControls(this);` but this may be a bad idea (I'm still checking the ramifications of that approach).

**Comment by toolforger** [comment]
I'm dropping this, see my other post on DSLification.
