### ISSUE TITLE
Double subscription of annotation-based events

### ISSUE THREAD

**Issue by mkaring** [nifty-gui/nifty-gui#55]
Its possible to subscribe the same events more then once by calling the `subscripeAnnoations` function of Nifty twice. That shouldn't be possible and throw a error or at least a warning.

The effect of the double subscription is that all events are published twice to the listeners.

**Comment by void256** [comment]
See commit comment for a description of the fix!

@mkaring would be nice if you can test this. however the current 1.4 has some first click oddity, right now: https://github.com/relu91/nifty-gui/commit/9acfdf2da377ceb0b7a2bbc89467092bfb994c2d#commitcomment-6100802

I'll close the issue now anyway. Please re-open if this fix does not work as expected.

**Comment by void256** [comment]
Doesn't work with ReferenceStrength.WEAK ... damn

**Comment by void256** [comment]
Contacted the author on Twitter, found out the project is on github :smile: and created a bug report for what I think is the issue here: https://github.com/michaelbushe/EventBus/issues/1

**Comment by void256** [comment]
Should work better now. Anyone able to test this?

**Comment by void256** [comment]
I'll close the issue for now and hope this time I can keep it closed :wink:

**Comment by BorealFeast** [comment]
edit: I'll create a new issue since this one is closed.

Hi!
I'm currently migrating from 1.3.2 to 1.4.1 and i found an issue with the NiftyEventSubscriber annotation. To be short, I have two screenControllers subscribing with the NiftyEventSubscriber annotation with the same pattern. This worked well in 1.3.2 since only the current screen received the event. Now in 1.4.1, the event is thrown in both of my screenControllers. What If found is the went I move from Screen1 to AnotherScreen2, the Screen1 controller is never unsubscribed from the eventBus, which seems to be related to the next piece of code in the ThreadSafeEventService.class of EventBus. With the latest commit related to issue #55, the Subscriber private class no longer implements ProxySubscriber. The next piece of code then always returns null. 

```
private ProxySubscriber getProxySubscriber(List subscribers, Object subscribedByProxy) {
      for (Iterator iter = subscribers.iterator(); iter.hasNext();) {
         Object subscriber = iter.next();
         if (subscriber instanceof WeakReference) {
            WeakReference wr = (WeakReference) subscriber;
            subscriber = wr.get();
         }
         if (subscriber instanceof ProxySubscriber) {
            ProxySubscriber proxy = (ProxySubscriber) subscriber;
            subscriber = proxy.getProxiedSubscriber();
            if (subscriber == subscribedByProxy) {
               return proxy;
            }
         }
      }
      return null;
   }
```

And at the line 84 of NiftyEventAnnotationProcessor, this will always return false:  

```
77  private static void patternProcess(final Object obj, final Method method, final boolean add, @Nonnull final String topicPattern, final Class<?> eventClass, @Nonnull final EventService eventService) {
78    Pattern pattern = Pattern.compile(topicPattern);
79    if (add) {
80      Subscriber subscriber = new Subscriber(obj, method, eventClass);
81      eventService.subscribeStrongly(pattern, subscriber);
82      log.fine("-> subscribe [" + pattern + "] -> [" + subscriber + "]");
83    } else {
84      eventService.unsubscribe(pattern, obj);
85      log.fine("<- unsubscribe [" + pattern + "] -> [" + obj + "]");
86    }
87  }
```
