### ISSUE TITLE
BitBlt??

### ISSUE THREAD

**Issue by rhavin** [nifty-gui/nifty-gui#93]
I have an Image (with alpha) and want to copy … lets say … image-coordinates x, y, w, h into current panel at position a,b. How can i do this…??

To be more specific: Im inside EffectImpl.execute of an effect, set upon a panel, and i have an Image (BufferedImage or com.jme3.texture.Image, having it as com.jme3.Texture would be OK) already as pointer ready to use.

So i now need to copy coordinates 10,10,10,10 at 20,20 and coordinates 10,20,10,10 at 30,40 and coordinates … you got it.

In grafic2D, there is that reasonable simple function BitBlt. What is the alpha-aware(!) equivalent in Nifty? And … yes… i read about "subImageDirect" but i cant figure out how that would be useful in here.

I need something like r.renderQuadFromImage(x,y,w,h, image, ix, iy)…

**Comment by void256** [comment]
I agree that this would be a nice method to have but Nifty does not provide it at the moment. Currently there are no methods in Nifty RenderDevice that would allow direct access to image content. I'm considering this for Nifty 2.0 but at the moment you can't have that in Nifty 1.x

There are two workarounds possible I think:

a) You use [the subImageDirect suggestion at sf.net](http://sourceforge.net/p/nifty-gui/discussion/807893/thread/e8607707/#43be) which would allow you to render a part of an image although I agree that this is a bit awkward to use for your usecase.

b) Since you seem to already use internals from jme3 why not use the methods jme3 provides for this? You could for instance use jme3 specifc methods to directly draw into a NiftyImage (which you would need to cast to the jme3 specifc implementation for this to work of course) and then render this NiftyImage as a whole.

Sorry that there are no other options available right now.

**Comment by void256** [comment]
I'll close this issue now. Current Nifty 1.x is not really prepared for that but Nifty 2.x will :smile:
